(function(root){
  const {planEquipmentSpaces}=root.equipmentSpacePlanner||(typeof require==='function'?require('./equipmentSpacePlanner'):{});
  const mm=(v)=>Math.round(Number(v)||0), idOf=(f)=>String(f.floorId||f.level||f.id||'1');
  const area=(r)=>Math.max(1,(Number(r.width)||0)*(Number(r.height||r.depth)||0)/1000000);
  const ctr=(r={})=>({x:mm((r.x||0)+(r.width||0)/2),y:mm((r.y||0)+(r.height||r.depth||0)/2)});
  const rect=(id,type,floor,x,y,width,depth,extra={})=>({id,type,floor,x:mm(x),y:mm(y),width:mm(width),depth:mm(depth),...extra});
  function floorsOf(input={}){return input.floorPlan?.floors||input.floors||[];}
  function roomsOf(input={}){const fs=floorsOf(input), listed=input.rooms||input.roomList||[]; return fs.flatMap(f=>(f.rooms||[]).map(r=>({...r,floor:idOf(f)}))).concat(listed.map(r=>({...r,floor:r.floor||r.floorId||'1'})));}
  function spacesOf(input,floors){return input.equipmentSpace||input.equipmentSpaces||(planEquipmentSpaces?planEquipmentSpaces({floorPlan:input.floorPlan||{floors},totalFloorArea:input.totalFloorArea,buildingUse:input.buildingUse}):{equipmentSpaces:[]});}
  function space(spaces,pattern,fallback){return (spaces.equipmentSpaces||spaces||[]).find(s=>pattern.test(s.type||s.name||''))||fallback;}
  function shaft(spaces,type,floor){const all=(spaces.equipmentSpaces||spaces||[]).filter(s=>(s.type||s.name)===type); return all.find(s=>String(s.floor)===String(floor))||all[0]||{floor,x:36000,y:24000,width:1200,depth:1800};}
  function route(id,system,from,to,floor,extra={}){const a={x:mm(from.x),y:mm(from.y)}, b={x:mm(to.x),y:mm(to.y)}, mid={x:a.x,y:b.y}; const length=Math.abs(a.x-mid.x)+Math.abs(a.y-mid.y)+Math.abs(mid.x-b.x); return {id,system,floor,method:'Graph Routing(EPS優先直交最短経路)',points:[a,mid,b],lengthMm:mm(length),...extra};}
  function roomLoad(r,cond={}){const n=r.name||'', z=r.zone||''; const base=z==='guest'?65:/厨房/.test(n)?180:/宴会|レストラン|ロビー|ホワイエ/.test(n)?105:/機械|電気/.test(n)?45:80; const demand=cond.demandFactor||0.78; return {roomId:r.roomId||r.id,name:n,floor:r.floor,areaM2:Number(area(r).toFixed(1)),lightingWm2:z==='guest'?8:/厨房/.test(n)?14:10,outletsVA:Number((area(r)*(z==='guest'?35:/厨房/.test(n)?90:45)).toFixed(1)),powerKw:Number((area(r)*base*demand/1000).toFixed(1)),emergency:/ロビー|宴会|廊下|階段|厨房/.test(n)||['corridor','safety'].includes(z),lanPorts:Math.max(1,Math.ceil(area(r)/(z==='guest'?25:45)))};}
  function powerReceiving(loads,spaces,input={}){const totalKw=loads.reduce((a,l)=>a+l.powerKw+l.outletsVA/1000+l.areaM2*l.lightingWm2/1000,0); const kva=Math.max(300,Math.ceil(totalKw/(input.electricalConditions?.powerFactor||0.9)/50)*50); const room=space(spaces,/受変電室/,{floor:'B1',x:42000,y:0,width:9000,depth:7200}); const er=space(spaces,/電気室/,{floor:room.floor,x:room.x,y:room.y+7200,width:9000,depth:5400}); return {id:'PR-1',system:kva>=500?'高圧6.6kV受電':'低圧受電',floor:room.floor,room:'受変電室',x:mm(room.x+600),y:mm(room.y+600),capacityKva:kva,incoming:'地中引込',highVoltagePanels:[rect('HV-1','高圧受電盤',room.floor,room.x+600,room.y+600,1200,900),rect('HV-2','高圧き電盤',room.floor,room.x+2100,room.y+600,1200,900)],lowVoltagePanels:[rect('LV-1','低圧動力盤',er.floor,er.x+600,er.y+600,1500,900),rect('LV-2','低圧電灯盤',er.floor,er.x+2400,er.y+600,1500,900)]};}
  function transformers(pr,spaces){const room=space(spaces,/受変電室/,{floor:pr.floor,x:42000,y:0,width:9000,depth:7200}); const n=Math.max(2,Math.ceil(pr.capacityKva/750)); return Array.from({length:n},(_,i)=>rect(`TR-${i+1}`,i?'動力変圧器':'電灯変圧器',room.floor,room.x+600+i*2100,room.y+2100,1800,1500,{capacityKva:Math.ceil(pr.capacityKva/n),oilLess:true}));}
  function panels(loads,spaces){const floors=[...new Set(loads.map(l=>l.floor))]; return floors.flatMap(f=>{const eps=shaft(spaces,'EPS',f), c=ctr(eps), fl=loads.filter(l=>l.floor===f); const cap=Math.ceil(fl.reduce((a,l)=>a+l.powerKw+l.outletsVA/1000,0)/10)*10; return [rect(`LP-${f}`,'分電盤',f,c.x+900,c.y-600,800,300,{capacityKva:Math.max(20,cap),serves:fl.map(l=>l.roomId)}),rect(`IDF-${f}`,'IDF盤',f,c.x+900,c.y+100,800,300,{lanPorts:fl.reduce((a,l)=>a+l.lanPorts,0)})];});}
  function lighting(loads,rooms){return loads.flatMap(l=>{const r=rooms.find(x=>(x.roomId||x.id)===l.roomId&&x.floor===l.floor)||{}; const c=ctr(r), count=Math.max(1,Math.ceil(l.areaM2/18)); return Array.from({length:Math.min(count,6)},(_,i)=>({id:`L-${l.roomId}-${i+1}`,type:'LED照明',floor:l.floor,roomId:l.roomId,x:mm(c.x+(i%3-1)*1800),y:mm(c.y+(Math.floor(i/3)-.5)*1800),watt:32,control:l.areaM2>80?'ゾーン制御':'個別スイッチ'}));});}
  function safety(loads,rooms){const targets=loads.filter(l=>l.emergency); return {emergencyLighting:targets.map(l=>{const c=ctr(rooms.find(r=>(r.roomId||r.id)===l.roomId&&r.floor===l.floor)||{}); return {id:`EL-${l.roomId}`,type:'非常照明',floor:l.floor,roomId:l.roomId,x:c.x,y:c.y,batteryMinutes:30};}),exitSigns:targets.filter(l=>/ロビー|宴会|廊下|階段/.test(l.name)).map(l=>{const c=ctr(rooms.find(r=>(r.roomId||r.id)===l.roomId&&r.floor===l.floor)||{}); return {id:`EX-${l.roomId}`,type:'誘導灯',floor:l.floor,roomId:l.roomId,x:mm(c.x+1200),y:c.y,direction:'避難口・通路'};})};}
  function generator(pr,spaces){const r=space(spaces,/発電機室/,{floor:'B1',x:51000,y:0,width:9000,depth:7200}); return {generator:rect('GEN-1','非常用発電機',r.floor,r.x+900,r.y+900,3600,1800,{capacityKva:Math.max(120,Math.ceil(pr.capacityKva*.3)),fuelHours:10,serves:['非常照明','誘導灯','自火報','防災負荷']}),ups:rect('UPS-1','UPS',r.floor,r.x+5100,r.y+900,1800,1200,{capacityKva:Math.max(20,Math.ceil(pr.capacityKva*.05)),backupMinutes:10})};}
  function weak(loads,rooms){return {fireAlarm:loads.map(l=>{const c=ctr(rooms.find(r=>(r.roomId||r.id)===l.roomId&&r.floor===l.floor)||{}); return {id:`FA-${l.roomId}`,type:/厨房/.test(l.name)?'熱感知器':'煙感知器',floor:l.floor,roomId:l.roomId,x:c.x,y:c.y};}),broadcast:loads.filter((_,i)=>i%2===0).map(l=>({id:`SPK-${l.roomId}`,type:'非常放送スピーカー',floor:l.floor,roomId:l.roomId})),lan:loads.map(l=>({id:`LAN-${l.roomId}`,floor:l.floor,roomId:l.roomId,ports:l.lanPorts,category:'Cat6A'}))};}
  function ascii(title,items){return ['+--------------------------------+',`| ${title.padEnd(30,' ')} |`,...items.slice(0,7).map(i=>`| ${String(i.id||i.type).padEnd(12,' ')} ${String(i.floor||'').padEnd(6,' ')} |`),'+--------------------------------+'].join('\n');}
  function score(loads,routes,checks){const len=routes.reduce((a,r)=>a+r.lengthMm,0), main=Math.max(8,18-Math.round(len/250000)); const total=Math.min(100,20+main+12+12+10+10+10+8-(checks.conflicts.length*2)); return {total,items:{powerReliability:20,mainRouteLength:main,constructability:12,maintainability:12,renewability:10,disasterPrevention:10,energySaving:10,codeCompliance:8}};}
  function planElectrical(input={}){const floors=floorsOf(input), spaces=spacesOf(input,floors), rooms=roomsOf(input).filter(r=>!['shaft','stair'].includes(r.zone)); const loads=rooms.map(r=>roomLoad(r,input.electricalConditions||{})); const pr=powerReceiving(loads,spaces,input), trs=transformers(pr,spaces), pbs=panels(loads,spaces); const fls=[...new Set(loads.map(l=>l.floor))]; const mainRoutes=fls.map(f=>route(`FEED-${f}`,'幹線',ctr(space(spaces,/電気室/,{x:pr.x,y:pr.y,width:1,depth:1,floor:pr.floor})),ctr(shaft(spaces,'EPS',f)),f,{via:'EPS',cable:'CVT'})); const branches=loads.map(l=>route(`BR-${l.roomId}`,'分岐配線',ctr(shaft(spaces,'EPS',l.floor)),ctr(rooms.find(r=>(r.roomId||r.id)===l.roomId&&r.floor===l.floor)||{}),l.floor,{via:'EPS'})); const racks=mainRoutes.map(r=>({...r,id:r.id.replace('FEED','RACK'),system:'ケーブルラック',widthMm:300})); const light=lighting(loads,rooms), safe=safety(loads,rooms), standby=generator(pr,spaces), low=weak(loads,rooms); const conflicts=[...mainRoutes,...branches].filter(r=>r.lengthMm>90000).map(r=>({target:r.id,type:'long-route',severity:'low'})); const sc=score(loads,[...mainRoutes,...branches],{conflicts}); return {schemaVersion:'1.0.0',engine:'Step9-8 Electrical Placement Engine',powerReceiving:pr,transformers:trs,panelBoards:pbs,lighting:light,emergencyLighting:safe.emergencyLighting,exitSigns:safe.exitSigns,cableNetwork:[...mainRoutes,...branches],cableRacks:racks,generator:standby.generator,ups:standby.ups,fireAlarm:low.fireAlarm,broadcast:low.broadcast,lan:low.lan,loadSchedule:loads,singleLineDiagram:ascii('単線結線図',[pr,...trs,...pr.highVoltagePanels,...pr.lowVoltagePanels]),receivingSystemDiagram:ascii('受変電系統図',[pr,...trs]),improvements:sc.total>=90?['成立性が高い。詳細設計で短絡容量、電圧降下、盤面寸法を確認する。']:['EPS近傍に盤を集約し、幹線長とケーブルラック交差を低減する。'],interferenceChecks:conflicts,score:sc,checklist:{mainRouteEstablished:mainRoutes.length>0,epsUsed:[...mainRoutes,...branches].every(r=>r.via==='EPS'),panelBoardsPlaced:pbs.some(p=>p.type==='分電盤'),lightingEstablished:light.length>0,emergencyLightingEstablished:safe.emergencyLighting.length>0,exitSignsEstablished:safe.exitSigns.length>0,generatorEstablished:!!standby.generator,fireAlarmEstablished:low.fireAlarm.length>0,lanEstablished:low.lan.length>0,examLevelCompatible:sc.total>=80}};}
  const api={planElectrical,PowerReceivingPlanner:{plan:powerReceiving},TransformerPlanner:{plan:transformers},MainDistributionPlanner:{},PanelBoardPlanner:{plan:panels},CableRackPlanner:{},CableRoutingEngine:{route},LightingPlanner:{plan:lighting},EmergencyLightingPlanner:{},ExitSignPlanner:{},GeneratorPlanner:{plan:generator},UPSPlanner:{},FireAlarmPlanner:{},BroadcastPlanner:{},LANPlanner:{},ElectricalScorer:{score}}; if(typeof module!=='undefined')module.exports=api; root.electricalPlacementEngine=api;
})(typeof window!=='undefined'?window:globalThis);
