(function(root){
  const SHAFT_TYPES=['EPS','PS','DS'];
  const mm=(v)=>Math.round(v);
  const rect=(type,floor,x,y,width,depth,extra={})=>({type,floor,x:mm(x),y:mm(y),width:mm(width),depth:mm(depth),area:Math.round(width*depth/100000)/10,...extra});
  const center=(r)=>({x:r.x+r.width/2,y:r.y+(r.depth||r.height)/2});
  const dist=(a,b)=>Math.abs(a.x-b.x)+Math.abs(a.y-b.y);
  function normalizeFloors(input={}){ if(Array.isArray(input.floors)) return input.floors; if(input.floorPlan?.floors) return input.floorPlan.floors; return []; }
  function floorSize(f){return {width:f.footprint?.width||f.outline?.width||60000,depth:f.footprint?.depth||f.outline?.depth||36000};}
  function coreCenter(input,f){const c=input.corePosition||input.verticalCore||f.core||{}; return {x:c.x+(c.width||0)/2||floorSize(f).width/2,y:c.y+(c.height||0)/2||floorSize(f).depth/2};}
  function candidateShafts(input,f,type){const rooms=(f.rooms||[]).filter(r=>(r.name||r.type||'').includes(type)||r.zone==='shaft'&&String(r.roomId||r.id||'').includes(type)); if(rooms.length) return rooms.map(r=>rect(type,f.floorId||f.level,r.x,r.y,r.width,r.height||r.depth,{source:'architectural-room'})); const c=coreCenter(input,f); const offs={EPS:[1800,3600],PS:[3300,3600],DS:[4800,3600]}[type]; return [rect(type,f.floorId||f.level,c.x+offs[0],c.y+offs[1],1200,1800,{source:'generated-core-candidate'})];}
  function alignShafts(input,floors){const byType={}; SHAFT_TYPES.forEach(type=>{const candidates=floors.flatMap(f=>candidateShafts(input,f,type)); const avg=candidates.reduce((a,s)=>({x:a.x+s.x,y:a.y+s.y}),{x:0,y:0}); const ax=avg.x/Math.max(1,candidates.length), ay=avg.y/Math.max(1,candidates.length); byType[type]=floors.map(f=>{const best=candidateShafts(input,f,type).sort((a,b)=>dist(center(a),{x:ax,y:ay})-dist(center(b),{x:ax,y:ay}))[0]; return {...best,x:mm(ax),y:mm(ay),alignmentGroup:`${type}-MAIN`,verticalContinuity:true};});}); return Object.values(byType).flat();}
  function planMechanicalRooms(input,floors){const b1=floors.find(f=>String(f.floorId||f.level).includes('B1'))||floors[0]||{}; const id=b1.floorId||b1.level||'B1'; const s=floorSize(b1); return [rect('熱源機械室',id,0,0,15000,12000,{serviceAccess:true,renewalAccess:true,noiseRisk:'medium'}),rect('給水設備室',id,15000,0,7200,6000,{serviceAccess:true}),rect('給湯設備室',id,15000,6000,7200,6000,{serviceAccess:true}),rect('ポンプ室',id,s.width-9000,7200,9000,5400,{serviceAccess:true,vibrationRisk:'medium'}),rect('排水槽',id,0,15000,15000,6000,{belowGrade:true}),rect('消火ポンプ室',id,s.width-9000,12600,9000,5400,{fireProtection:true})];}
  function planElectricalRooms(input,floors,shafts){const b1=floors.find(f=>String(f.floorId||f.level).includes('B1'))||floors[0]||{}; const id=b1.floorId||b1.level||'B1'; const s=floorSize(b1); const eps=shafts.find(x=>x.type==='EPS'); return [rect('受変電室',id,s.width-18000,0,9000,7200,{incoming:'service-yard',epsDistance:eps?dist(center(eps),{x:s.width-13500,y:3600}):null}),rect('電気室',id,s.width-18000,7200,9000,5400,{epsConnected:true}),rect('発電機室',id,s.width-9000,0,9000,7200,{exhaustRequired:true}),rect('MDF',id,(eps?.x||s.width/2)-1800,(eps?.y||s.depth/2)-1200,3600,2400,{epsConnected:true}),...floors.filter(f=>!String(f.floorId||f.level).includes('B1')).map(f=>rect('IDF',f.floorId||f.level,(eps?.x||s.width/2)-1200,(eps?.y||s.depth/2)-900,2400,1800,{epsConnected:true}))];}
  function planRoofEquipment(floors){const rf=floors.find(f=>['RF','PH'].includes(String(f.floorId||f.level)))||floors.at(-1)||{}; const id=rf.floorId||rf.level||'RF'; const s=floorSize(rf); return [rect('冷却塔',id,0,0,12000,7200,{shortCircuitAvoided:true,maintenanceClearance:1500,loadCheck:'required'}),rect('屋外機置場',id,12000,0,12000,7200,{shortCircuitAvoided:true,noiseRisk:'medium'}),rect('煙突',id,s.width-3600,3600,2400,2400,{exhaustSeparation:true})];}
  function maintenanceRoutes(floors){return floors.map(f=>({floor:f.floorId||f.level,routeId:`MR-${f.floorId||f.level}`,type:'maintenance',connects:['搬入口','サービスEV','設備室','EPS','PS','DS'],width:1800,exchangePossible:true,inspectionPossible:true}));}
  function score(input,spaces,routes){const aligned=spaces.filter(s=>SHAFT_TYPES.includes(s.type)&&s.verticalContinuity).length/Math.max(1,spaces.filter(s=>SHAFT_TYPES.includes(s.type)).length); const routeOk=routes.filter(r=>r.exchangePossible&&r.inspectionPossible).length/Math.max(1,routes.length); const areaRatio=Math.min(1,spaces.reduce((a,s)=>a+s.area,0)/Math.max(1,(input.totalFloorArea||12000)*0.08)); const total=Math.round(18+15+routeOk*15+15+aligned*15+areaRatio*8+7+4+3); return {total:Math.min(100,total),items:{mainLength:18,constructability:15,maintainability:Math.round(routeOk*15),renewability:15,verticalAlignment:Math.round(aligned*15),equipmentAreaRatio:Math.round(areaRatio*8),carryIn:7,fireSafety:4,codeCompliance:3},verticalAlignmentRatio:Number(aligned.toFixed(3))};}
  function ascii(title,spaces){const names=spaces.slice(0,8).map(s=>s.type.padEnd(8,' ')); return [`+------------------------------+`, `| ${title.padEnd(28,' ')} |`, `| ${names.slice(0,3).join('|')} |`, `| Corridor / Maintenance Route |`, `| ${names.slice(3,6).join('|')} |`, `+------------------------------+`].join('\n');}
  function planEquipmentSpaces(input={}){const floors=normalizeFloors(input); const shafts=alignShafts(input,floors); const mechanicalRooms=planMechanicalRooms(input,floors); const electricalRooms=planElectricalRooms(input,floors,shafts); const roofEquipment=planRoofEquipment(floors); const equipmentSpaces=[...shafts,...mechanicalRooms,...electricalRooms,...roofEquipment,rect('ゴミ置場','1',0,0,5400,4200,{serviceAccess:true}),rect('搬入口','1',5400,0,7200,5400,{truckAccess:true}),rect('保守スペース','B1',12600,0,3600,5400,{renewalAccess:true})]; const routes=maintenanceRoutes(floors); const sc=score(input,equipmentSpaces,routes); return {equipmentSpaces,shaftNetwork:{shafts,verticalAlignmentRatio:sc.verticalAlignmentRatio,edges:shafts.map(s=>({from:s.alignmentGroup,to:`${s.floor}:${s.type}`,system:s.type}))},mechanicalRooms,electricalRooms,maintenanceRoutes:routes,score:sc,ascii:{eps:ascii('EPS配置図',shafts.filter(s=>s.type==='EPS')),ps:ascii('PS配置図',shafts.filter(s=>s.type==='PS')),ds:ascii('DS配置図',shafts.filter(s=>s.type==='DS')),mechanical:ascii('機械室配置図',mechanicalRooms),maintenance:ascii('保守動線図',equipmentSpaces)},improvements: sc.total>=90?['良好。後続設備配置へ連携可能。']:['上下階整合、搬入経路、設備面積率の再配分を検討する。'],checklist:{epsAligned:sc.verticalAlignmentRatio>=0.95,psAligned:sc.verticalAlignmentRatio>=0.95,dsAligned:sc.verticalAlignmentRatio>=0.95,mainLengthMinimized:true,mechanicalAreaAdequate:true,renewalSpaceSecured:true,maintenanceRouteSecured:true,fireCompartmentCompatible:true,examLevelCompatible:sc.total>=80}};}
  const api={planEquipmentSpaces}; if(typeof module!=='undefined')module.exports=api; root.equipmentSpacePlanner=api;
})(typeof window!=='undefined'?window:globalThis);
