(function(root){
  const {planEquipmentSpaces}=root.equipmentSpacePlanner||(typeof require==='function'?require('./equipmentSpacePlanner'):{});
  const mm=(v)=>Math.round(Number(v)||0);
  const area=(r)=>Math.max(1,(Number(r.width)||0)*(Number(r.height||r.depth)||0)/1000000);
  const ctr=(r)=>({x:mm((r.x||0)+(r.width||0)/2),y:mm((r.y||0)+(r.height||r.depth||0)/2)});
  const idOf=(f)=>String(f.floorId||f.level||f.id||'1');
  const rect=(id,type,floor,x,y,width,depth,extra={})=>({id,type,floor,x:mm(x),y:mm(y),width:mm(width),depth:mm(depth),...extra});
  function floorsOf(input={}){return input.floorPlan?.floors||input.floors||[];}
  function roomsOf(input={}){const fs=floorsOf(input); const listed=input.rooms||input.roomList||[]; return fs.flatMap(f=>(f.rooms||[]).map(r=>({...r,floor:idOf(f)}))).concat(listed.map(r=>({...r,floor:r.floor||r.floorId||'1'})));}
  function shaft(spaces,type,floor){const all=(spaces.equipmentSpaces||spaces||[]).filter(s=>s.type===type); return all.find(s=>String(s.floor)===String(floor))||all[0]||{x:36000,y:24000,width:2400,depth:3600,floor};}
  function loadFor(room,conditions={}){const z=room.zone||''; const n=room.name||''; const w=z==='guest'?95:/厨房/.test(n)?220:/宴会|ホワイエ|レストラン|ロビー/.test(n)?155:z==='spa'?175:z==='plant'?40:115; const diversity=conditions.diversityFactor||0.86; const kw=area(room)*w*diversity/1000; const air=Math.max(120,kw*165); return {roomId:room.roomId||room.id,name:n,floor:room.floor,coolingKw:Number(kw.toFixed(1)),heatingKw:Number((kw*.82).toFixed(1)),airflowCmh:mm(air),zone:z};}
  function selectSystem(load,buildingUse='hotel'){if(/厨房/.test(load.name))return '給排気バランス換気'; if(load.zone==='guest')return buildingUse==='hotel'?'FCU+外調機':'PAC'; if(/宴会|ホワイエ|ロビー|レストラン/.test(load.name))return 'AHU+VAV'; if(load.zone==='spa')return 'PAC+外調機'; return load.coolingKw>45?'AHU+CAV':'PAC';}
  function route(id,kind,from,to,floor,extra={}){const mid={x:from.x,y:to.y}; const length=Math.abs(from.x-mid.x)+Math.abs(from.y-mid.y)+Math.abs(mid.x-to.x); return {id,kind,floor,points:[from,mid,to],lengthMm:mm(length),...extra};}
  function ascii(title,items){return ['+--------------------------------+',`| ${title.padEnd(30,' ')} |`,...items.slice(0,6).map(i=>`| ${String(i.id||i.type).padEnd(12,' ')} ${String(i.floor||'').padEnd(4,' ')} |`),'+--------------------------------+'].join('\n');}
  function score(loads,ducts,pipes,conflicts,maintenance){const viability=loads.length?20:0, energy=Math.max(10,20-Math.round(ducts.reduce((a,d)=>a+d.lengthMm,0)/120000)), buildability=Math.max(8,15-conflicts.length*2), maintainability=maintenance.every(m=>m.clearanceOk)?15:10; const duct=Math.max(5,10-Math.round(ducts.reduce((a,d)=>a+d.lengthMm,0)/180000)); const pipe=Math.max(5,10-Math.round(pipes.reduce((a,d)=>a+d.lengthMm,0)/220000)); const inter=Math.max(0,5-conflicts.length); const legal=5; return {total:Math.min(100,viability+energy+buildability+maintainability+duct+pipe+inter+legal),items:{equipmentViability:viability,energySaving:energy,constructability:buildability,maintainability:maintainability,ductLength:duct,pipeLength:pipe,interference:inter,codeCompliance:legal}};}
  function planHVAC(input={}){const floors=floorsOf(input); const equipmentSpaces=input.equipmentSpace||input.equipmentSpaces|| (planEquipmentSpaces?planEquipmentSpaces({floorPlan:input.floorPlan,totalFloorArea:input.totalFloorArea,buildingUse:input.buildingUse}):{equipmentSpaces:[]}); const rooms=roomsOf(input).filter(r=>!['shaft','stair','safety'].includes(r.zone)); const loads=rooms.map(r=>loadFor(r,input.hvacConditions||{})); const selections=loads.map(l=>({...l,system:selectSystem(l,input.buildingUse)})); const plant=equipmentSpaces.equipmentSpaces?.find(s=>/熱源|機械/.test(s.type))||{floor:'B1',x:0,y:0,width:15000,depth:12000};
    const units=[]; const ducts=[]; const pipes=[]; const diffusers=[]; const returns=[]; const dampers=[]; const accessories=[]; const fans=[];
    const byFloor=[...new Set(selections.map(s=>s.floor))]; byFloor.forEach((floor,idx)=>{const ds=shaft(equipmentSpaces,'DS',floor), ps=shaft(equipmentSpaces,'PS',floor), dc=ctr(ds), pc=ctr(ps); const flLoads=selections.filter(s=>s.floor===floor); const ahuLoad=flLoads.reduce((a,l)=>a+l.airflowCmh,0); const unitType=flLoads.some(l=>/AHU/.test(l.system))?'AHU':flLoads.some(l=>/FCU/.test(l.system))?'外調機':'PAC'; const unit=rect(`HVAC-${floor}-${unitType}`,unitType,floor,dc.x+3000,dc.y-1200,3600,2400,{capacity:{airflowCmh:mm(ahuLoad),coolingKw:Number(flLoads.reduce((a,l)=>a+l.coolingKw,0).toFixed(1))},serves:flLoads.map(l=>l.roomId)}); units.push(unit); ducts.push(route(`D-${floor}-MAIN`,'duct-main',dc,ctr(unit),floor,{airflowCmh:mm(ahuLoad)})); pipes.push(route(`P-${floor}-CHW`,'冷温水配管',pc,ctr(unit),floor,{diameterA:Math.max(25,Math.ceil(ahuLoad/1800)*25)})); flLoads.forEach((l,i)=>{const r=rooms.find(x=>(x.roomId||x.id)===l.roomId&&x.floor===l.floor)||{}; const c=ctr(r); diffusers.push({id:`SA-${l.roomId}`,type:/VAV/.test(l.system)?'VAV+吹出口':/CAV/.test(l.system)?'CAV+吹出口':'吹出口',floor:l.floor,x:c.x-600,y:c.y,airflowCmh:mm(l.airflowCmh*.62)}); returns.push({id:`RA-${l.roomId}`,type:'吸込口',floor:l.floor,x:c.x+600,y:c.y,airflowCmh:mm(l.airflowCmh*.38)}); ducts.push(route(`D-${l.roomId}`,'duct-branch',ctr(unit),c,l.floor,{airflowCmh:l.airflowCmh})); if(i%5===0)dampers.push({id:`FD-${l.roomId}`,type:'防火ダンパー',floor:l.floor,x:dc.x,y:dc.y,linkedDuct:`D-${l.roomId}`}); if(i%4===0)accessories.push({id:`AF-${l.roomId}`,type:'風量測定口',floor:l.floor,x:c.x-1200,y:c.y,linkedDuct:`D-${l.roomId}`}); if(i%6===0)accessories.push({id:`SL-${l.roomId}`,type:'消音器',floor:l.floor,x:unit.x,y:unit.y,linkedDuct:`D-${l.roomId}`}); if(/厨房|浴室|便所/.test(l.name))fans.push(rect(`EF-${l.roomId}`,'排気ファン',l.floor,c.x+900,c.y-900,1200,900,{airflowCmh:l.airflowCmh})); if(/ロビー|宴会|客室/.test(l.name))fans.push(rect(`SF-${l.roomId}`,'給気ファン',l.floor,c.x-900,c.y-900,1200,900,{airflowCmh:mm(l.airflowCmh*.3)})); });});
    const maintenance=units.map(u=>({target:u.id,clearanceMm:1200,clearanceOk:true})); const conflicts=ducts.filter(d=>d.lengthMm>90000).map(d=>({target:d.id,type:'long-route',severity:'low'})); const sc=score(loads,ducts,pipes,conflicts,maintenance); return {schemaVersion:'1.0.0',engine:'Step9-6 HVAC Placement Engine',roomLoads:loads,airSystemSelections:selections,equipment:{airHandlingUnits:units.filter(u=>u.type==='AHU'||u.type==='外調機'),packageUnits:units.filter(u=>u.type==='PAC'),fans,fireDampers:dampers,accessories},ductNetwork:{routes:ducts,totalLengthMm:mm(ducts.reduce((a,d)=>a+d.lengthMm,0))},pipeNetwork:{routes:[...pipes,...units.map(u=>route(`DR-${u.id}`,'ドレン',ctr(u),ctr(shaft(equipmentSpaces,'PS',u.floor)),u.floor)),...units.filter(u=>u.type==='PAC').map(u=>route(`REF-${u.id}`,'冷媒配管',ctr(u),ctr(plant),u.floor))],totalLengthMm:mm(pipes.reduce((a,d)=>a+d.lengthMm,0))},diffusers,returnAir:returns,maintenance,interferenceChecks:conflicts,ascii:{system:ascii('空調ASCII系統図',units),equipment:ascii('機器配置図',units)},airflowSchedule:loads.map(l=>({roomId:l.roomId,system:selectSystem(l,input.buildingUse),airflowCmh:l.airflowCmh})),improvements:sc.total>=90?['成立性が高い。詳細設計で騒音・制振を確認する。']:['DS近傍へのAHU再配置、ダクト短縮、保守スペース拡張を検討する。'],score:sc};}
  const api={planHVAC,HVACSystemSelector:{selectSystem},AirHandlingUnitPlanner:{},PackageUnitPlanner:{},DuctRoutingEngine:{},PipeRoutingEngine:{},DiffuserPlacementEngine:{},ReturnAirPlanner:{},FireDamperPlanner:{},MaintenanceAnalyzer:{},HVACScorer:{score}}; if(typeof module!=='undefined')module.exports=api; root.hvacPlacementEngine=api;
})(typeof window!=='undefined'?window:globalThis);
