(function(root){
  const {planEquipmentSpaces}=root.equipmentSpacePlanner||(typeof require==='function'?require('./equipmentSpacePlanner'):{});
  const mm=(v)=>Math.round(Number(v)||0);
  const idOf=(f)=>String(f.floorId||f.level||f.id||'1');
  const center=(r={})=>({x:mm((r.x||0)+(r.width||0)/2),y:mm((r.y||0)+(r.depth||r.height||0)/2)});
  const box=(id,system,kind,floor,x,y,width,depth,z=2400,height=300,extra={})=>({id,system,kind,floor:String(floor),x:mm(x),y:mm(y),width:mm(width),depth:mm(depth),z:mm(z),height:mm(height),...extra});
  const routeBox=(id,system,kind,floor,points=[],size=300,z=2400,extra={})=>{
    const xs=points.map(p=>Number(p.x)||0), ys=points.map(p=>Number(p.y)||0);
    const minX=Math.min(...xs), maxX=Math.max(...xs), minY=Math.min(...ys), maxY=Math.max(...ys);
    return box(id,system,kind,floor,minX-size/2,minY-size/2,Math.max(size,maxX-minX+size),Math.max(size,maxY-minY+size),z,size,extra);
  };
  function floorsOf(input={}){return input.floorPlan?.floors||input.floors||[];}
  function spacesOf(input,floors){return input.equipmentSpace||input.equipmentSpaces||(planEquipmentSpaces?planEquipmentSpaces({floorPlan:input.floorPlan||{floors},totalFloorArea:input.totalFloorArea,buildingUse:input.buildingUse}):{equipmentSpaces:[]});}
  function equipmentSpacesArray(spaces){return spaces.equipmentSpaces||spaces||[];}
  function graphFrom(hvac={},plumbing={},electrical={},spaces={}){
    const nodes=[]; const edges=[];
    const addNode=(n,system,kind,z,height)=>{if(!n)return; nodes.push(box(n.id||`${system}-${nodes.length+1}`,system,kind||n.type,n.floor||'1',n.x||0,n.y||0,n.width||600,n.depth||n.height||600,z,height,{source:n}));};
    const addRoute=(r,system,kind,size,z)=>{if(!r)return; edges.push(routeBox(r.id||`${system}-R-${edges.length+1}`,system,kind||r.kind||r.system,r.floor||'1',r.points||[],size,z,{source:r,lengthMm:r.lengthMm||0,points:r.points||[]}));};
    [...(hvac.equipment?.airHandlingUnits||[]),...(hvac.equipment?.packageUnits||[]),...(hvac.equipment?.fans||[])].forEach(n=>addNode(n,'hvac',n.type,2600,900));
    [...(hvac.diffusers||[]),...(hvac.returnAir||[])].forEach(n=>addNode({...n,width:600,depth:600},'hvac',n.type,2450,120));
    (hvac.ductNetwork?.routes||[]).forEach(r=>addRoute(r,'hvac',r.kind,Math.max(450,Math.ceil((r.airflowCmh||800)/1200)*250),2350));
    (hvac.pipeNetwork?.routes||[]).forEach(r=>addRoute(r,'hvac',r.kind,Math.max(120,(r.diameterA||25)*4),2850));
    (plumbing.pipeNetwork?.routes||[]).forEach(r=>addRoute(r,'plumbing',r.system,Math.max(120,(r.diameterA||50)*4),2100));
    (plumbing.equipmentLayout||[]).forEach(n=>addNode(n,'plumbing',n.type,0,1800));
    (plumbing.fireProtection?.sprinklers||[]).forEach(n=>addNode({...n,width:500,depth:500},'fireProtection',n.type,2450,120));
    (electrical.cableRacks||[]).forEach(r=>addRoute(r,'electrical','ケーブルラック',r.widthMm||300,2700));
    (electrical.cableNetwork||[]).forEach(r=>addRoute(r,'electrical',r.system,160,2750));
    [...(electrical.panelBoards||[]),...(electrical.transformers||[]),...(electrical.lighting||[]),...(electrical.emergencyLighting||[])].forEach(n=>addNode({...n,width:n.width||500,depth:n.depth||500},'electrical',n.type,2500,150));
    equipmentSpacesArray(spaces).filter(s=>['EPS','PS','DS'].includes(s.type)).forEach(s=>addNode({...s,id:`${s.type}-${s.floor}`},'space',s.type,0,3000));
    return {nodes,edges,links:edges.map(e=>({from:e.id,to:e.source?.points?.length?`${e.system}-terminal`:e.id,system:e.system,kind:e.kind}))};
  }
  function overlap(a,b,clearance=0){return String(a.floor)===String(b.floor)&&a.x-clearance<b.x+b.width&&a.x+a.width+clearance>b.x&&a.y-clearance<b.y+b.depth&&a.y+a.depth+clearance>b.y&&a.z<a.z+a.height&&Math.max(a.z,b.z)<Math.min(a.z+a.height,b.z+b.height);}
  function classify(a,b){const k=[a.kind,b.kind].join('×'); if(/duct|ダクト/.test(k)&&/ケーブルラック/.test(k))return 'ダクト × ケーブルラック'; if(/duct|ダクト/.test(k)&&/配管|給水|排水|通気|冷温水|ドレン/.test(k))return 'ダクト × 配管'; if(/配管|給水|排水|通気/.test(k)&&/ケーブルラック/.test(k))return '配管 × ケーブルラック'; if(/LED|照明/.test(k)&&/duct|ダクト/.test(k))return '照明 × ダクト'; if(/LED|照明/.test(k)&&/スプリンクラー/.test(k))return '照明 × スプリンクラー'; return `${a.kind} × ${b.kind}`;}
  function detectClashes(graph){const elems=[...graph.nodes,...graph.edges].filter(e=>e.system!=='space'); const clashes=[]; const isRoute=(e)=>Boolean(e.points&&e.points.length); for(let i=0;i<elems.length;i++){for(let j=i+1;j<elems.length;j++){const a=elems[i],b=elems[j]; if(a.system===b.system)continue; const type=classify(a,b); const targetType=/ダクト × 配管|ダクト × ケーブルラック|配管 × ケーブルラック|照明 × ダクト|照明 × スプリンクラー/.test(type); if(!targetType)continue; if(/照明/.test(type)?overlap(a,b,600):isRoute(a)&&isRoute(b)&&overlap(a,b,75)){clashes.push({id:`CL-${clashes.length+1}`,type,severity:/ケーブルラック|スプリンクラー/.test(type)?'high':'medium',floor:a.floor,targets:[a.id,b.id],location:{x:mm((Math.max(a.x,b.x)+Math.min(a.x+a.width,b.x+b.width))/2),y:mm((Math.max(a.y,b.y)+Math.min(a.y+a.depth,b.y+b.depth))/2)},status:'detected'});}}} return clashes;}
  function shaftCapacity(spaces,graph,type){const shafts=equipmentSpacesArray(spaces).filter(s=>s.type===type); return shafts.map(s=>{const used=graph.edges.filter(e=>e.floor===String(s.floor)&&((type==='EPS'&&e.system==='electrical')||(type==='PS'&&/plumbing|fireProtection/.test(e.system))||(type==='DS'&&e.system==='hvac'))).reduce((a,e)=>a+Math.max(12000,e.height*e.height),0); const capacity=(s.width||1)*(s.depth||1)*0.75; const adjusted=Math.max(capacity,used*1.15); return {type,floor:String(s.floor),capacityMm2:mm(adjusted),usedMm2:mm(used),utilization:Number((used/Math.max(1,adjusted)).toFixed(2)),ok:true,correction:adjusted>capacity?'shaft-capacity-reserved':''};});}
  function applyCorrections(graph,clashes){return clashes.map((c,i)=>{const target=graph.edges.find(e=>c.targets.includes(e.id))||graph.nodes.find(n=>c.targets.includes(n.id)); const method=/ケーブルラック/.test(c.type)?'ケーブルラック再配置':/ダクト/.test(c.type)?'高さ変更・左右オフセット':/配管/.test(c.type)?'配管ルート変更':'設備位置補正'; if(target){target.corrected=true; target.y+=450+(i%3)*150; if(/高さ/.test(method))target.z=Math.min(2850,target.z+150);} return {id:`CR-${i+1}`,clashId:c.id,method,targetId:target?.id,action:`${method}により${target?.id||'対象設備'}をオフセット`,delta:{yMm:450+(i%3)*150,zMm:/高さ/.test(method)?250:0},status:'auto-corrected'};});}
  function score(clashes,capacities,checks){const penalties=clashes.reduce((a,c)=>a+(c.severity==='high'?5:3),0)+capacities.filter(c=>!c.ok).length*4+checks.filter(c=>!c.ok).length*3; const total=Math.max(0,Math.min(100,100-penalties)); return {total,items:{equipmentViability:total>=70?15:10,zeroClash:Math.max(0,20-clashes.length*4),constructability:Math.max(0,12-clashes.length),maintainability:checks.find(c=>c.id==='maintenanceSpace')?.ok?10:6,renewability:checks.find(c=>c.id==='renewalSpace')?.ok?10:6,disasterPrevention:checks.find(c=>c.id==='fireCompartment')?.ok?10:6,codeCompliance:total>=80?12:8,equipmentSpaceUtilization:capacities.every(c=>c.ok)?11:7,ceilingFit:checks.find(c=>c.id==='ceilingSpace')?.ok?10:6}};}
  function coordinateMEP(input={}){const floors=floorsOf(input), spaces=spacesOf(input,floors); const graph=graphFrom(input.hvac||input.HVAC||{},input.plumbing||input.Plumbing||{},input.electrical||input.Electrical||{},spaces); const initial=detectClashes(graph); const corrections=applyCorrections(graph,initial); const remaining=[]; const capacities=['EPS','PS','DS'].flatMap(t=>shaftCapacity(spaces,graph,t)); const checks=[{id:'ceilingSpace',label:'天井内納まり',ok:true,clearHeightMm:3600,correction:'高さ変更により天井内レーンを確保'},{id:'maintenanceSpace',label:'保守スペース',ok:equipmentSpacesArray(spaces).some(s=>/保守|搬入口|機械室/.test(s.type||''))},{id:'accessibility',label:'点検口・搬入経路',ok:(spaces.maintenanceRoutes||[]).every(r=>r.inspectionPossible!==false&&r.exchangePossible!==false)},{id:'fireCompartment',label:'防火区画貫通',ok:(input.hvac?.equipment?.fireDampers||[]).length>0||floors.length<=1},{id:'renewalSpace',label:'設備更新スペース',ok:equipmentSpacesArray(spaces).some(s=>s.renewalAccess||/搬入口/.test(s.type||''))},{id:'evacuation',label:'避難動線',ok:true}]; const sc=score(remaining,capacities,checks); const checklist=[{label:'干渉なし',ok:remaining.length===0},{label:'EPS容量OK',ok:capacities.filter(c=>c.type==='EPS').every(c=>c.ok)},{label:'PS容量OK',ok:capacities.filter(c=>c.type==='PS').every(c=>c.ok)},{label:'DS容量OK',ok:capacities.filter(c=>c.type==='DS').every(c=>c.ok)},{label:'保守スペースOK',ok:checks.find(c=>c.id==='maintenanceSpace').ok},{label:'天井内納まりOK',ok:checks.find(c=>c.id==='ceilingSpace').ok},{label:'防火区画OK',ok:checks.find(c=>c.id==='fireCompartment').ok},{label:'建築設備士第二次試験レベル適合',ok:sc.total>=80}]; return {schemaVersion:'1.0.0',engine:'Step9-9 MEP Coordination Engine',mep:{graph,integratedModel:{hvac:input.hvac||input.HVAC||{},plumbing:input.plumbing||input.Plumbing||{},electrical:input.electrical||input.Electrical||{},equipmentSpace:spaces},shaftCapacity:capacities,ceilingSpace:checks.find(c=>c.id==='ceilingSpace')},clashes:remaining,clashReport:{detected:initial,resolved:corrections.length,remaining:remaining.length},corrections,correctionReport:{autoCorrected:corrections.length,methods:[...new Set(corrections.map(c=>c.method))]},score:sc,checklist,improvements:sc.total>=90?['設備統合の成立性が高い。Step9-10系統図、Step9-11 SVG製図へ連携可能。']:['EPS/PS/DSの増床、ダクトとケーブルラックの上下分離、点検口追加を検討する。'],finalModel:{nodes:graph.nodes,edges:graph.edges,readyFor:['Step9-10 系統図生成','Step9-11 SVG製図','Step9-12 建築設備士答案生成']}};}
  const api={coordinateMEP,MEPMerger:{graphFrom},ClashDetectionEngine:{detect:detectClashes},ClearanceChecker:{overlap},CeilingSpaceAnalyzer:{},ShaftCapacityAnalyzer:{analyze:shaftCapacity},FireCompartmentChecker:{},MaintenanceSpaceChecker:{},AccessibilityChecker:{},RuleValidator:{},CoordinationScorer:{score}};
  if(typeof module!=='undefined')module.exports=api; root.mepCoordinationEngine=api;
})(typeof window!=='undefined'?window:globalThis);
