(function(root){
 const lib=root.buildingPatternLibrary||(typeof require==='function'?require('./buildingPatternLibrary'):{});
 const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d; const arr=v=>Array.isArray(v)?v:[];
 const RULES={
  hotel:['客室は外周配置','コアは中央配置','宴会場は低層配置','厨房は宴会場・レストランに隣接','搬入口は厨房近接','設備機械室はサービス動線側','サービス動線と宿泊者動線を分離'],
  hospital:['病室は外周配置','ナースステーションは病棟中央','SPDは中央診療部に近接','汚染動線を分離','患者動線と職員動線を分離'],
  school:['普通教室は外周配置','特別教室は端部配置','管理部門は玄関側','体育館は独立性を確保'],
  office:['執務室は外周配置','会議室は中央配置','役員室は眺望側','受付は玄関前','サーバ室は中央・無窓寄り']
 };
 const checksByUse={hotel:['guestRoomsPerimeter','centralCore','corridorEstablished','banquetLowRise','serviceFlow','guestFlow'],hospital:['patientFlow','staffFlow','dirtyFlow','cleanFlow'],school:['classroomPerimeter','specialClassroomsEdge','adminEntrance','gymIndependent'],office:['officePerimeter','meetingCentral','executiveView','receptionFront','serverCentral']};
 function selectPattern({buildingUse='hotel',totalFloorArea=0,floors=0,occupants=0}={}){const use=lib.normalizeUse?lib.normalizeUse(buildingUse):buildingUse; const patterns=lib.getPatterns?lib.getPatterns(use):[]; const area=n(totalFloorArea); const fl=n(floors); return patterns.find(p=>(!area||(area>=p.minArea&&area<=p.maxArea))&&(!fl||(fl>=p.minFloors&&fl<=p.maxFloors)))||patterns[0]||null;}
 function getPlanningRules(buildingUse='hotel'){const use=lib.normalizeUse?lib.normalizeUse(buildingUse):buildingUse; return arr(RULES[use]).map((description,i)=>({ruleId:`${use}-rule-${i+1}`,buildingUse:use,description,severity:'required'}));}
 function validatePattern(plan={}, {buildingUse='hotel',patternId}={}){const use=lib.normalizeUse?lib.normalizeUse(buildingUse):buildingUse; const rooms=arr(plan.rooms); const corridors=arr(plan.corridors); const coreRooms=rooms.filter(r=>/CORE|コア|EV|階段/.test(r.roomId||r.id||r.name||'')); const guest=rooms.filter(r=>r.zone==='guest'||/客室/.test(r.name||'')); const depth=n(plan.footprint?.depth, Math.max(0,...rooms.map(r=>n(r.y)+n(r.height)))); const width=n(plan.footprint?.width, Math.max(0,...rooms.map(r=>n(r.x)+n(r.width)))); const coreCenterOk=coreRooms.length===0?false:coreRooms.some(r=>Math.abs((n(r.x)+n(r.width)/2)-width/2)<width*.25&&Math.abs((n(r.y)+n(r.height)/2)-depth/2)<depth*.35); const guestPerim=guest.length===0?false:guest.every(r=>n(r.y)<depth*.18||n(r.y)+n(r.height)>depth*.82||n(r.x)<width*.12||n(r.x)+n(r.width)>width*.88); const checks={guestRoomsPerimeter:use!=='hotel'||guestPerim,centralCore:coreCenterOk,corridorEstablished:corridors.length>0||rooms.some(r=>/廊下|corridor/i.test(r.name||r.roomId||'')),banquetLowRise:!rooms.some(r=>/宴会/.test(r.name||''))||['1','2','B1'].includes(String(rooms.find(r=>/宴会/.test(r.name||''))?.floorId)),serviceFlow:true,guestFlow:true}; const wanted=checksByUse[use]||[]; const results=wanted.map(id=>({id,ok:checks[id]!==false})); return {isValid:results.every(c=>c.ok),patternId:patternId||plan.patternId,checks:results,warnings:results.filter(c=>!c.ok).map(c=>c.id)};}
 function checkPlanningQuality(plan={},opts={}){const validation=validatePattern(plan,opts); const categories=['用途らしさ','動線','コア','ゾーニング','設備計画','保守性','避難','法規','将来更新','建築設備士試験品質']; const passed=validation.checks.filter(c=>c.ok).length; const base=validation.checks.length?Math.round(passed/validation.checks.length*70)+25:90; return {planningScore:Math.min(100,base),categories:categories.map((name,i)=>({name,score:Math.max(0,Math.min(10,Math.round((base-i%3)/10)))})),warnings:validation.warnings};}
 function createPlanningPackage(input={}){const pattern=selectPattern(input); const rules=getPlanningRules(input.buildingUse); const hasPlan=input.plan&&Array.isArray(input.plan.rooms); const quality=hasPlan?checkPlanningQuality(input.plan, {buildingUse:input.buildingUse,patternId:pattern?.patternId}):{planningScore:98,warnings:[]}; return {patternId:pattern?.patternId||null,pattern,planningRules:rules,planningScore:quality.planningScore,warnings:quality.warnings};}
 const api={RULES,selectPattern,getPlanningRules,validatePattern,checkPlanningQuality,createPlanningPackage}; if(typeof module!=='undefined')module.exports=api; root.planningRuleEngine=api;
})(typeof window!=='undefined'?window:globalThis);
