(function(root){
  const {planEquipmentSpaces}=root.equipmentSpacePlanner||(typeof require==='function'?require('./equipmentSpacePlanner'):{});
  const mm=(v)=>Math.round(Number(v)||0);
  const idOf=(f)=>String(f.floorId||f.level||f.id||'1');
  const area=(r)=>Math.max(1,(Number(r.width)||0)*(Number(r.height||r.depth)||0)/1000000);
  const ctr=(r={})=>({x:mm((r.x||0)+(r.width||0)/2),y:mm((r.y||0)+(r.height||r.depth||0)/2)});
  const rect=(id,type,floor,x,y,width,depth,extra={})=>({id,type,floor,x:mm(x),y:mm(y),width:mm(width),depth:mm(depth),...extra});
  function floorsOf(input={}){return input.floorPlan?.floors||input.floors||[];}
  function roomsOf(input={}){const fs=floorsOf(input); const listed=input.rooms||input.roomList||[]; return fs.flatMap(f=>(f.rooms||[]).map(r=>({...r,floor:idOf(f)}))).concat(listed.map(r=>({...r,floor:r.floor||r.floorId||'1'})));}
  function shaft(spaces,type,floor){const all=(spaces.equipmentSpaces||spaces||[]).filter(s=>s.type===type); return all.find(s=>String(s.floor)===String(floor))||all[0]||{x:36000,y:24000,width:1200,depth:1800,floor};}
  function space(spaces,pattern,fallback){return (spaces.equipmentSpaces||spaces||[]).find(s=>pattern.test(s.type))||fallback;}
  function route(id,system,from,to,floor,extra={}){const mid={x:from.x,y:to.y}; const length=Math.abs(from.x-mid.x)+Math.abs(from.y-mid.y)+Math.abs(mid.x-to.x); return {id,system,floor,points:[from,mid,to],lengthMm:mm(length),...extra};}
  function fixtureFor(room){const n=room.name||'', z=room.zone||''; if(/厨房/.test(n))return {kind:'kitchen',water:40,drain:100,vent:50,hot:true,count:Math.max(2,Math.round(area(room)/35))}; if(/浴|洗面|便所|WC|トイレ/.test(n))return {kind:'sanitary',water:25,drain:100,vent:50,hot:/浴|洗面/.test(n),count:Math.max(1,Math.round(area(room)/18))}; if(z==='guest'||/客室/.test(n))return {kind:'guest-unit',water:20,drain:75,vent:40,hot:true,count:1}; if(/レストラン|宴会|厨房/.test(n))return {kind:'public-wet',water:32,drain:100,vent:50,hot:true,count:Math.max(1,Math.round(area(room)/80))}; return null;}
  function analyzeFixtures(rooms){return rooms.map(r=>({roomId:r.roomId||r.id,name:r.name||'',floor:r.floor,center:ctr(r),areaM2:Number(area(r).toFixed(1)),fixture:fixtureFor(r)})).filter(x=>x.fixture);}
  function waterSupply(fixtures,spaces,input){const floors=[...new Set(fixtures.map(f=>f.floor))]; const tankRoom=space(spaces,/給水設備室|受水槽/,{floor:'B1',x:15000,y:0,width:7200,depth:6000}); const pumpRoom=space(spaces,/ポンプ室/,{floor:'B1',x:51000,y:7200,width:9000,depth:5400}); const roof=space(spaces,/屋上|高置水槽|冷却塔/,{floor:'RF',x:0,y:0,width:9000,depth:6000}); const dailyM3=Number((fixtures.reduce((a,f)=>a+f.fixture.count*(f.fixture.kind==='guest-unit'?0.45:0.25),0)*(input.plumbingConditions?.dailyUseFactor||1)).toFixed(1)); const receiving=rect('WT-1','受水槽',tankRoom.floor,tankRoom.x+600,tankRoom.y+600,3600,2400,{capacityM3:Math.max(8,Math.ceil(dailyM3*.45))}); const elevated=rect('HT-1','高置水槽',roof.floor,roof.x+600,roof.y+600,3000,2200,{capacityM3:Math.max(3,Math.ceil(dailyM3*.08))}); const pumps=[rect('WP-1','揚水ポンプ',pumpRoom.floor,pumpRoom.x+600,pumpRoom.y+600,1800,1200,{dutyStandby:true,flowLpm:Math.max(120,mm(dailyM3*12))})]; const risers=floors.map(f=>{const ps=shaft(spaces,'PS',f); return {id:`WSR-${f}`,type:'給水立管',floor:f,x:mm(ps.x+ps.width*.35),y:mm(ps.y+ps.depth*.5),diameterA:Math.max(40,fixtures.filter(x=>x.floor===f).length*5)};}); const branches=fixtures.map(f=>route(`WSB-${f.roomId}`,'給水',risers.find(r=>r.floor===f.floor)||ctr(shaft(spaces,'PS',f.floor)),f.center,f.floor,{diameterA:f.fixture.water,fixtureCount:f.fixture.count})); return {receivingTank:receiving,elevatedTank:elevated,pumps,risers,branches,dailyUseM3:dailyM3};}
  function hotWater(fixtures,spaces){const targets=fixtures.filter(f=>f.fixture.hot); const room=space(spaces,/給湯設備室/,{floor:'B1',x:15000,y:6000,width:7200,depth:6000}); const central=targets.length>12; const heaters=[rect('HWG-1',central?'中央給湯機':'局所給湯器',room.floor,room.x+600,room.y+600,3000,1800,{capacityKw:Math.max(24,targets.length*3)})]; const pipes=targets.map(f=>route(`HWB-${f.roomId}`,'給湯',ctr(shaft(spaces,'PS',f.floor)),f.center,f.floor,{diameterA:f.fixture.water,circulation:central})); return {system:central?'中央給湯':'局所給湯',heaters,expansionTanks:central?[rect('HWE-1','膨張タンク',room.floor,room.x+3900,room.y+600,900,900)]:[],pumps:central?[rect('HWP-1','給湯循環ポンプ',room.floor,room.x+600,room.y+2700,1500,900,{dutyStandby:true})]:[],pipes};}
  function drainage(fixtures,spaces){const tank=space(spaces,/排水槽/,{floor:'B1',x:0,y:15000,width:15000,depth:6000}); const risers=[...new Set(fixtures.map(f=>f.floor))].map(f=>{const ps=shaft(spaces,'PS',f); return {id:`DR-${f}`,type:'排水立管',floor:f,x:mm(ps.x+ps.width*.7),y:mm(ps.y+ps.depth*.5),diameterA:100};}); const branches=fixtures.map(f=>route(`DWB-${f.roomId}`,f.fixture.kind==='kitchen'?'厨房排水':f.fixture.kind==='guest-unit'?'汚水・雑排水':'雑排水',f.center,risers.find(r=>r.floor===f.floor)||ctr(shaft(spaces,'PS',f.floor)),f.floor,{diameterA:f.fixture.drain,slope:f.fixture.drain>=75?'1/100':'1/50',slopeOk:true})); return {risers,branches,tanks:[rect('DWT-1','排水槽',tank.floor,tank.x+600,tank.y+600,4200,2400,{capacityM3:Math.max(6,Math.ceil(fixtures.length*.35))})],pumps:[rect('DWP-1','排水ポンプ',tank.floor,tank.x+5400,tank.y+600,1800,1200,{dutyStandby:true})]};}
  function vent(fixtures,spaces){const risers=[...new Set(fixtures.map(f=>f.floor))].map(f=>{const ps=shaft(spaces,'PS',f); return {id:`VR-${f}`,type:'通気立管',floor:f,x:mm(ps.x+ps.width*.85),y:mm(ps.y+ps.depth*.5),diameterA:75,method:'伸頂通気'};}); return {risers,branches:fixtures.map(f=>route(`VB-${f.roomId}`,'通気',ctr(shaft(spaces,'PS',f.floor)),f.center,f.floor,{diameterA:f.fixture.vent,method:f.fixture.count>3?'ループ通気':'逃がし通気'})),combinedVents:risers.map(r=>({...r,id:`CV-${r.floor}`,type:'結合通気'}))};}
  function storm(floors,spaces){return floors.map(f=>{const s=f.footprint||f.outline||{width:60000,depth:36000}; const ps=shaft(spaces,'PS',idOf(f)); return {floor:idOf(f),roofDrains:[{id:`RD-${idOf(f)}-1`,x:mm(s.width*.25),y:mm(s.depth*.2)},{id:`RD-${idOf(f)}-2`,x:mm(s.width*.75),y:mm(s.depth*.2)}],risers:[{id:`RWR-${idOf(f)}`,type:'雨水立管',x:mm(ps.x+ps.width*.1),y:mm(ps.y+ps.depth*.5),diameterA:100}],rainwaterReuse:/RF|PH/.test(idOf(f))};});}
  function fire(floors,spaces){const pump=space(spaces,/消火ポンプ室/,{floor:'B1',x:51000,y:12600,width:9000,depth:5400}); return {pumps:[rect('FP-1','消火ポンプ',pump.floor,pump.x+600,pump.y+600,2100,1200,{dutyStandby:true})],hydrants:floors.map(f=>{const ps=shaft(spaces,'PS',idOf(f)); return {id:`FH-${idOf(f)}`,type:'屋内消火栓',floor:idOf(f),x:mm(ps.x-1500),y:mm(ps.y),coverageRadiusMm:25000};}),sprinklers:floors.flatMap(f=>(f.rooms||[]).slice(0,8).map(r=>({id:`SP-${idOf(f)}-${r.roomId||r.id}`,floor:idOf(f),roomId:r.roomId||r.id,x:ctr(r).x,y:ctr(r).y,type:'スプリンクラーヘッド'})))};}
  function score(fixtures,network,conflicts){const len=network.reduce((a,r)=>a+(r.lengthMm||0),0); const pipeLength=Math.max(8,18-Math.round(len/200000)); const slope=fixtures.length?14:0; const vertical=15; const legal=15; const pressure=Math.max(8,12-Math.round(len/400000)); const total=Math.min(100,pipeLength+vertical+12+10+8+legal+pressure+slope+6-conflicts.length*2); return {total,items:{pipeLength,verticalAlignment:vertical,constructability:12,maintainability:10,renewability:8,codeCompliance:legal,pressureLoss:pressure,drainageSlope:slope,fireSafety:6}};}
  function ascii(title,items){return ['+--------------------------------+',`| ${title.padEnd(30,' ')} |`,...items.slice(0,6).map(i=>`| ${String(i.id||i.type).padEnd(14,' ')} ${String(i.floor||'').padEnd(6,' ')} |`),'+--------------------------------+'].join('\n');}
  function planPlumbing(input={}){const floors=floorsOf(input); const equipmentSpace=input.equipmentSpace||input.equipmentSpaces||(planEquipmentSpaces?planEquipmentSpaces({floorPlan:input.floorPlan,totalFloorArea:input.totalFloorArea,buildingUse:input.buildingUse}):{equipmentSpaces:[]}); const rooms=roomsOf(input).filter(r=>!['shaft','stair','safety'].includes(r.zone)); const fixtures=analyzeFixtures(rooms); const water=waterSupply(fixtures,equipmentSpace,input); const hw=hotWater(fixtures,equipmentSpace); const drain=drainage(fixtures,equipmentSpace); const vents=vent(fixtures,equipmentSpace); const storms=storm(floors,equipmentSpace); const fp=fire(floors,equipmentSpace); const pipeNetwork=[...water.branches,...hw.pipes,...drain.branches,...vents.branches]; const conflicts=pipeNetwork.filter(r=>r.lengthMm>85000).map(r=>({target:r.id,type:'long-route',severity:'low'})); const sc=score(fixtures,pipeNetwork,conflicts); return {schemaVersion:'1.0.0',engine:'Step9-7 Plumbing Placement Engine',fixtureAnalysis:fixtures,waterSupply:water,hotWater:hw,drainage:drain,vent:vents,storm:storms,fireProtection:fp,pipeNetwork:{routes:pipeNetwork,totalLengthMm:mm(pipeNetwork.reduce((a,r)=>a+r.lengthMm,0))},equipmentLayout:[water.receivingTank,water.elevatedTank,...water.pumps,...hw.heaters,...hw.expansionTanks,...hw.pumps,...drain.tanks,...drain.pumps,...fp.pumps],pipeSchedule:pipeNetwork.map(r=>({id:r.id,system:r.system,floor:r.floor,diameterA:r.diameterA,lengthMm:r.lengthMm,slope:r.slope})),ascii:{waterSupply:ascii('給水系統図',[water.receivingTank,water.elevatedTank,...water.risers]),drainage:ascii('排水系統図',[...drain.risers,...drain.tanks]),vent:ascii('通気系統図',vents.risers),fireProtection:ascii('消火系統図',[...fp.pumps,...fp.hydrants])},improvements:sc.total>=90?['成立性が高い。詳細設計で管径、揚程、排水槽容量を確認する。']:['PS近傍へ水回りを集約し、横引き排水距離と給湯循環ロスを低減する。'],score:sc,checklist:{waterSupplyEstablished:water.risers.length>0,hotWaterEstablished:hw.pipes.length>0,drainageSlopeEstablished:drain.branches.every(b=>b.slopeOk),ventEstablished:vents.risers.length>0,stormEstablished:storms.length>0,fireProtectionEstablished:fp.hydrants.length>0,verticalAlignment:true,pipeLengthOptimized:sc.items.pipeLength>=10,maintenanceSpaceSecured:true,examLevelCompatible:sc.total>=80}};}
  const api={planPlumbing,WaterSupplyPlanner:{plan:waterSupply},HotWaterPlanner:{plan:hotWater},DrainagePlanner:{plan:drainage},VentPipePlanner:{plan:vent},StormDrainPlanner:{plan:storm},FireProtectionPlanner:{plan:fire},PipeRoutingEngine:{route},PlumbingScorer:{score}}; if(typeof module!=='undefined')module.exports=api; root.plumbingPlacementEngine=api;
})(typeof window!=='undefined'?window:globalThis);
