const arr = (v) => Array.isArray(v) ? v : (v ? [v] : []);
const commonQuestions = (common) => Array.isArray(common) ? common : Object.values(common || {});
const text = (v) => typeof v === 'string' ? v : JSON.stringify(v || '');
const norm = (s) => String(s || '').replace(/ＣＱ/g, 'CQ').replace(/Ｑ/g, 'Q').toUpperCase();
const canonicalQid = (id) => norm(id).replace(/^Q0([345])$/, 'CQ0$1');
const includes = (obj, token) => text(obj).includes(token);
const getCommon = (exam) => commonQuestions(exam?.common).map((q) => ({ ...q, canonicalQuestionId: canonicalQid(q.questionId || q.id) }));
const COMMON_IDS = ['CQ03', 'CQ04', 'CQ05'];
const ALLOWED_HVAC = ['FCU二管式','FCU四管式','PAC','PAC+CAV','PAC+VAV','AHU+CAV','AHU+VAV','外調機','全熱交換器','厨房排気','排煙','加圧','EV前室','クリーンルーム'];
const PLUMBING_ROOMS = ['男子便所','女子便所','厨房','浴室','ランドリー','機械室','給湯室','厨房排水','客室UB','SPA'];
const ELECTRICAL_ITEMS = ['照明','感知器','非常放送','誘導灯','コンセント','配線','警戒範囲'];
const WEIGHTS = { Question: 20, Drawing: 20, AnswerSheet: 20, ModelAnswer: 15, Template: 15, Scale: 5, CrossReference: 5 };

function createCollector() {
  const checks = [], errors = [], warnings = [];
  return { checks, errors, warnings, check(category, name, ok, message, warn = false) { checks.push({ category, name, ok: !!ok, weight: WEIGHTS[category] || 0 }); if (!ok) (warn ? warnings : errors).push(message || `${name}の検査に失敗しました。`); } };
}
function score(checks) {
  return Object.entries(WEIGHTS).reduce((sum, [category, weight]) => {
    const cs = checks.filter((c) => c.category === category);
    if (!cs.length) return sum + weight;
    return sum + weight * (cs.filter((c) => c.ok).length / cs.length);
  }, 0);
}
function qText(q) { return [q.questionId, q.title, q.prompt, q.type, q.category, ...(q.conditions || []), ...(q.relatedSystems || []), ...(q.relatedRooms || []), text(q.autoSelection)].join(' '); }
function inferRoom(q) { const t = qText(q); return q.autoSelection?.roomType || q.relatedRooms?.[0] || [...PLUMBING_ROOMS, '7階客室', '客室', '宴会場', '地下食堂', 'レストラン', '地下駐車場'].find((r) => t.includes(r)); }
function inferHvac(q) { const t = qText(q).replace(/AHU\+VAV/g, 'AHU+VAV').replace(/AHU-VAV/g, 'AHU+VAV'); if (/四管式/.test(t)) return 'FCU四管式'; if (/二管式/.test(t)) return 'FCU二管式'; return ALLOWED_HVAC.find((x) => t.includes(x)); }
function answerSheetAreas(answerSheets) { const a4 = answerSheets?.answerSheet4 || {}; return [a4.floorPlanArea, a4.detailArea, a4.scheduleLegendArea].filter(Boolean); }
function findFor(id, collections) { return collections.find((x) => canonicalQid(x?.questionId || x?.blankPlan?.questionId || x?.id) === id || canonicalQid(x?.blankPlan?.questionMetadata?.questionId) === id); }

class QuestionConsistencyChecker { check(input, c) { const selection = input.exam?.selection || input.exam?.electiveSections || {}; const ids = [...arr(selection.hvac), ...arr(selection.plumbing), ...arr(selection.electrical), ...getCommon(input.exam)].map((q) => canonicalQid(q.questionId || q.id)); c.check('Question', '問題番号重複禁止', ids.length === new Set(ids).size, '問題番号が重複しています。'); [['A', selection.hvac, ['A01','A02']], ['B', selection.plumbing, ['B01','B02']], ['C', selection.electrical, ['C01','C02']]].forEach(([, qs, expected]) => c.check('Question', `${expected.join(',')}欠番禁止`, JSON.stringify(arr(qs).map((q) => q.questionId)) === JSON.stringify(expected), `${expected.join('～')}の問題番号に欠番または不整合があります。`)); c.check('Question', 'CQ03-CQ05欠番禁止', JSON.stringify(getCommon(input.exam).map((q) => q.canonicalQuestionId)) === JSON.stringify(COMMON_IDS), '共通問題はCQ03、CQ04、CQ05のみである必要があります。'); } }
class CommonQuestionChecker { check(input, c) { const all = text(input.exam); c.check('Question', 'A03/B03/C03生成禁止', !/\b[ABC]03\b/.test(all), 'A03、B03、C03は生成禁止です。'); const qs = getCommon(input.exam); c.check('Question', '共通問題3問のみ', qs.length === 3 && qs.every((q) => COMMON_IDS.includes(q.canonicalQuestionId)), '共通問題はCQ03、CQ04、CQ05のみです。'); qs.forEach((q) => { const id = q.canonicalQuestionId; const room = inferRoom(q); const mode = id === 'CQ03' ? inferHvac(q) : undefined; if (id === 'CQ03') c.check('CrossReference', `${id} HVAC方式`, !!mode && ALLOWED_HVAC.includes(mode), `${id}のHVAC方式が許可リストにありません。`); if (id === 'CQ04') c.check('CrossReference', `${id} Plumbing用途`, !!room && PLUMBING_ROOMS.some((r) => room.includes(r) || qText(q).includes(r)), `${id}の衛生対象室・用途が判定できません。`); if (id === 'CQ05') c.check('CrossReference', `${id} Electrical項目`, ELECTRICAL_ITEMS.some((x) => qText(q).includes(x)), `${id}の電気設備要求が判定できません。`); [input.drawings, input.answerSheets, input.modelAnswers, input.scoring].filter(Boolean).forEach((part) => { if (room) c.check('CrossReference', `${id} ${room}相互一致`, includes(part, room) || includes(input.answerSheets, room), `${id}は${room}問題ですが関連資料に同じ対象がありません。`); }); [input.answerSheets, input.modelAnswers, input.scoring].filter(Boolean).forEach((part) => { if (mode) c.check('CrossReference', `${id} ${mode}相互一致`, includes(part, mode) || includes(part, 'FCU') || includes(part, 'four-pipe') || includes(part, '外調機'), `${id}は${mode}ですが関連資料が一致しません。`); }); }); } }
class DrawingConsistencyChecker { check(input, c) { getCommon(input.exam).forEach((q) => { const room = inferRoom(q); if (room) c.check('Drawing', `${q.canonicalQuestionId}問題文と建築図`, includes(input.drawings, room) || includes(input.building, room) || includes(input.answerSheets, room), `問題は${room}ですが図面に同じ対象がありません。`); }); } }
class BlankPlanChecker { check(input, c) { const forbidden = ['設備機器','配管','ダクト','配線','照明','器具','機器番号','equipmentSpaces','pipes','ducts','wiring','equipmentSymbols']; arr(input.drawings?.blankPlans).forEach((p) => forbidden.forEach((f) => c.check('Drawing', `白図禁止:${f}`, !Object.prototype.hasOwnProperty.call(p, f) && !includes(p, f), `白図に禁止要素（${f}）が含まれています。`))); } }
class AnswerSheetChecker { check(input, c) { const a4 = input.answerSheets?.answerSheet4; c.check('AnswerSheet', 'AnswerSheet4存在', !!a4, 'AnswerSheet4がありません。'); c.check('AnswerSheet', 'AnswerSheet4共通問題専用', JSON.stringify(arr(a4?.questions).map((q) => canonicalQid(q.questionId))) === JSON.stringify(COMMON_IDS), 'AnswerSheet4はCQ03、CQ04、CQ05専用である必要があります。'); const areas = answerSheetAreas(input.answerSheets); COMMON_IDS.forEach((id) => { c.check('AnswerSheet', `${id}専用図面`, !!findFor(id, areas), `${id}専用図面がAnswerSheet4にありません。`); const q = getCommon(input.exam).find((item) => item.canonicalQuestionId === id); const area = findFor(id, areas); const expectedRoom = q && inferRoom(q); const actualRoom = area?.drawing?.blankPlan?.questionMetadata?.roomType || area?.drawing?.blankPlan?.drawingRequirement?.roomType; if (expectedRoom && actualRoom) c.check('AnswerSheet', `${id}答案用紙対象室一致`, actualRoom === expectedRoom || includes(actualRoom, expectedRoom) || includes(expectedRoom, actualRoom), `${id}答案用紙が${expectedRoom}ではありません。`); }); c.check('AnswerSheet', '固定レイアウト禁止', areas.every((a) => a?.drawing?.blankPlan?.sheetLayout?.adaptive), 'AnswerSheet4は問題別自動生成図面を使用する必要があります。'); } }
class ModelAnswerChecker { check(input, c) { if (!input.modelAnswers) return c.check('ModelAnswer', '模範解答未提供', true, '', true); getCommon(input.exam).forEach((q) => { const mode = inferHvac(q); if (mode) c.check('ModelAnswer', `${q.canonicalQuestionId}要求設備のみ`, includes(input.modelAnswers, mode) || includes(input.modelAnswers, 'FCU'), `${q.canonicalQuestionId}の模範解答設備が問題文と一致しません。`); }); } }
class ScoringChecker { check(input, c) { if (!input.scoring) return c.check('CrossReference', '採点基準未提供', true, '', true); COMMON_IDS.forEach((id) => c.check('CrossReference', `${id}採点基準`, includes(input.scoring, id) || includes(input.scoring, id.replace('CQ','Q')), `${id}の採点基準がありません。`)); } }
class ScaleChecker { check(input, c) { answerSheetAreas(input.answerSheets).forEach((a) => { const p = a?.drawing?.blankPlan; c.check('Scale', `${a.questionId}縮尺一致`, !p || !p.drawingRequirement?.requiredScale || p.scale === p.drawingRequirement.requiredScale, `${a.questionId}の縮尺が問題・白図・答案で一致しません。`); }); } }
class TemplateChecker { check(input, c) { const names = ['資料1','問題冊子','資料2','建築基本設計図','資料3','模範解答','資料4','設備模範図','資料5','答案用紙']; const hay = [input.materials, input.exam, input.drawings, input.modelAnswers, input.answerSheets].map(text).join(' '); names.forEach((name) => c.check('Template', `${name}構成維持`, name === '問題冊子' || name === '答案用紙' || name === '模範解答' || name === '設備模範図' || hay.includes(name) || hay.includes(name.replace(/資料\d/, '')), `${name}のテンプレート構成を確認できません。`, !['問題冊子','答案用紙'].includes(name)));  } }
class CrossReferenceChecker { check(input, c) { getCommon(input.exam).forEach((q) => { const id = q.canonicalQuestionId; const room = inferRoom(q); if (room) c.check('CrossReference', `${id}問題-図面-答案-模範-採点`, [input.drawings, input.answerSheets, input.modelAnswers, input.scoring].filter(Boolean).every((x) => includes(x, room) || includes(input.answerSheets, room)), `${id}の相互参照が${room}で一致しません。`); }); } }
class ExamConsistencyEngine { constructor() { this.checkers = [new QuestionConsistencyChecker(), new DrawingConsistencyChecker(), new CommonQuestionChecker(), new BlankPlanChecker(), new AnswerSheetChecker(), new ModelAnswerChecker(), new ScoringChecker(), new ScaleChecker(), new TemplateChecker(), new CrossReferenceChecker()]; } check(input = {}) { const c = createCollector(); this.checkers.forEach((checker) => checker.check(input, c)); const s = Math.round(score(c.checks)); return { passed: c.errors.length === 0 && s >= 95, score: s, warnings: c.warnings, errors: c.errors, checks: c.checks }; } }
function checkExamConsistency(input) { return new ExamConsistencyEngine().check(input); }
if (typeof module !== 'undefined') module.exports = { ExamConsistencyEngine, checkExamConsistency, QuestionConsistencyChecker, DrawingConsistencyChecker, CommonQuestionChecker, BlankPlanChecker, AnswerSheetChecker, ModelAnswerChecker, ScoringChecker, ScaleChecker, TemplateChecker, CrossReferenceChecker, ALLOWED_HVAC };
if (typeof window !== 'undefined') { window.ExamConsistencyEngine = ExamConsistencyEngine; window.checkExamConsistency = checkExamConsistency; }
