(function () {
  const p = (typeof require !== 'undefined') ? require('./svgPrimitives') : window.svgPrimitives;
  const esc = (v) => (p?.escapeXml ? p.escapeXml(v) : String(v ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c])));
  const css = `<style>@page{size:A4 portrait;margin:8mm}.answer-sheet-page{box-sizing:border-box;background:#fff;color:#000;border:1.5px solid #000;margin:0 auto 12px;padding:8mm;font-family:system-ui,sans-serif;page-break-after:always}.answer-sheet-page.a4{width:210mm;min-height:297mm}.answer-sheet-page.a3{width:420mm;min-height:297mm;padding:0}.answer-header{display:grid;grid-template-columns:1fr 45mm 60mm 28mm;gap:2mm;align-items:stretch;border-bottom:1px solid #000;padding-bottom:2mm}.answer-field,.answer-box{border:1px solid #000;min-height:10mm;padding:1mm}.answer-grid{background-image:linear-gradient(#ddd 1px,transparent 1px),linear-gradient(90deg,#ddd 1px,transparent 1px);background-size:5mm 5mm}.answer-lines{background:repeating-linear-gradient(#fff,#fff 7mm,#ccc 7.2mm)}.question-block{border:1px solid #000;margin-top:3mm;padding:2mm;break-inside:avoid}.area-row{display:grid;grid-template-columns:28mm 1fr;gap:2mm;margin-top:1.5mm}.disabled{display:none}.drawing-area{background:#fff;border:1.2px solid #000;min-height:90mm}.calc-table{width:100%;border-collapse:collapse}.calc-table th,.calc-table td{border:1px solid #000;height:9mm;font-size:10px}@media print{.no-print,button,select{display:none!important}body{background:#fff;color:#000}.answer-sheet-page{margin:0;border-color:#000}.answer-sheet-page.a3{page:answer-a3}@page answer-a3{size:A3 landscape;margin:0}svg{max-width:100%;height:auto}}</style>`;
  function header(sheet) { return `<div class="answer-header"><div><strong>${esc(sheet.title || '答案用紙')}</strong><br><small>${esc(sheet.sheetType || '')}</small></div><div class="answer-field">受験番号</div><div class="answer-field">氏名</div><div class="answer-field">答案番号</div></div>`; }
  function renderAreas(q, options) { return Object.values(q.areas || {}).map((a) => `<div class="area-row ${a.enabled ? '' : 'disabled'}"><div>${esc(a.label)}</div><div id="${esc(a.id)}" class="answer-box ${a.kind === 'description' ? (options.showGrid ? 'answer-grid' : 'answer-lines') : ''} ${a.kind === 'diagram' ? 'drawing-area' : ''}" style="min-height:${a.kind === 'calculation' ? '34mm' : a.kind === 'diagram' ? '45mm' : '22mm'}"></div></div>`).join(''); }
  function table(area) { const cols = area?.columns || []; return `<table id="${esc(area?.id)}" class="calc-table"><thead><tr>${cols.map((c) => `<th>${esc(c)}</th>`).join('')}</tr></thead><tbody>${Array.from({ length: 6 }, () => `<tr>${cols.map(() => '<td></td>').join('')}</tr>`).join('')}</tbody></table>`; }
  function renderHtml(sheet, options = {}) { const qhtml = (sheet.questions || []).map((q) => `<section class="question-block"><strong>第${esc(q.number)}問 ${options.showQuestionTitles === false ? '' : esc(q.title || q.sectionTitle)}</strong>${renderAreas(q, options)}</section>`).join(''); const extras = [sheet.calculationTable && table(sheet.calculationTable), sheet.systemDiagramArea && `<section class="question-block drawing-area" id="${esc(sheet.systemDiagramArea.id)}">系統図欄：${(sheet.systemDiagramArea.labels || []).map(esc).join('・')}</section>`, sheet.floorPlanArea && `<section class="question-block drawing-area" id="${esc(sheet.floorPlanArea.id)}">平面図欄${options.includeBlankPlanBackground ? '（白図背景参照）' : ''}</section>`, sheet.detailArea && `<section class="question-block drawing-area" id="${esc(sheet.detailArea.id)}">部分詳細図欄</section>`, sheet.scheduleLegendArea && `<section class="question-block" id="${esc(sheet.scheduleLegendArea.id)}">機器表・凡例・記述欄</section>`].filter(Boolean).join(''); return `${css}<article class="answer-sheet-page ${sheet.size === 'A3-landscape' ? 'a3' : 'a4'}">${header(sheet)}${qhtml}${extras}</article>`; }
  function rect(x, y, w, h, text, id) { return `${p.drawRect({ id, x, y, width: w, height: h, fill: '#fff', stroke: '#000', strokeWidth: 0.5 })}${text ? p.drawText({ x: x + 2, y: y + 5, text, textAnchor: 'start', fontSize: 3, fill: '#000' }) : ''}`; }
  function renderSvg(sheet, options = {}) { const W = 420, H = 297; const parts = [p.drawRect({ x: 4, y: 4, width: 412, height: 289, fill: '#fff', stroke: '#000', strokeWidth: 0.8 }), rect(8, 8, 250, 16, sheet.title || '答案用紙'), rect(260, 8, 45, 16, '答案番号'), rect(305, 8, 50, 16, '受験番号'), rect(355, 8, 55, 16, '氏名'), rect(8, 28, 190, 135, '作図領域 / 平面図領域', sheet.floorPlanArea?.id), rect(202, 28, 100, 70, `系統図領域 ${(sheet.systemDiagramArea?.labels || []).slice(0, 4).join('・')}`, sheet.systemDiagramArea?.id), rect(306, 28, 104, 70, '部分詳細図領域', sheet.detailArea?.id), rect(202, 102, 208, 60, '機器表・凡例欄', sheet.scheduleLegendArea?.id), rect(8, 168, 270, 85, '記述欄・計算欄'), rect(282, 168, 128, 85, '採点者欄')]; if (options.showGrid) for (let x = 13; x < 198; x += 5) parts.push(p.drawLine({ x1: x, y1: 33, x2: x, y2: 163, stroke: '#ddd', strokeWidth: 0.15 })); return `<svg xmlns="http://www.w3.org/2000/svg" width="420mm" height="297mm" viewBox="0 0 ${W} ${H}" role="img" aria-label="${esc(sheet.title)}"><style>text{font-family:sans-serif}.thin{stroke:#000}</style>${parts.join('')}</svg>`; }
  function renderAnswerSheet(answerSheet, options = {}) { return (options.mode === 'svg' || answerSheet?.size === 'A3-landscape') ? renderSvg(answerSheet, options) : renderHtml(answerSheet, options); }
  function renderAnswerSheetSet(set, options = {}) { const sheetType = options.sheetType; const sheets = ['mandatoryPlanningSheet','hvacSheet','plumbingSheet','electricalSheet','commonDescriptionSheet'].filter((k) => !sheetType || k === sheetType).map((k) => set?.[k]).filter(Boolean); return sheets.map((s) => renderAnswerSheet(s, options)).join('\n'); }
  const api = { renderAnswerSheet, renderAnswerSheetSet };
  if (typeof module !== 'undefined') module.exports = api; if (typeof window !== 'undefined') window.answerSheetRenderer = api;
}());
