(function(root){
 const p=root.svgPrimitives||(typeof require==='function'?require('./svgPrimitives'):{});
 const base=root.svgRenderer||(typeof require==='function'?require('./svgRenderer'):{});
 const qc=root.drawingQualityChecker||(typeof require==='function'?require('../layout/drawingQualityChecker'):{});
 const SHEETS={A3:{width:420,height:297},A2:{width:594,height:420},exam:{width:420,height:297}};
 const DISCIPLINES={architecture:{layer:'Layer01_Architecture',title:'建築平面図',no:'A-101'},hvac:{layer:'Layer04_Equipment',title:'空調設備図',no:'M-101'},plumbing:{layer:'Layer04_Equipment',title:'給排水設備図',no:'P-101'},electrical:{layer:'Layer04_Equipment',title:'電気設備図',no:'E-101'},equipment:{layer:'Layer04_Equipment',title:'設備平面図',no:'MEP-101'},system:{layer:'Layer04_Equipment',title:'設備系統図',no:'MEP-201'},detail:{layer:'Layer01_Architecture',title:'部分詳細図',no:'D-101'}};
 const esc=(v)=>p.escapeXml?p.escapeXml(v):String(v??'');
 function sheetOptions(o={}){const s=SHEETS[o.sheetSize]||SHEETS.A3;return{sheetSize:o.sheetSize||'A3',width:o.orientation==='portrait'?s.height:s.width,height:o.orientation==='portrait'?s.width:s.height,orientation:o.orientation||'landscape',scale:o.scale||'S=1/100',title:o.title||'設備図面',drawingNumber:o.drawingNumber||'MEP-000',projectTitle:o.projectTitle||'建築設備士 試験答案'};}
 function inject(svg,layer,content){const key=`<g id="${layer}"`;const i=svg.indexOf(key);if(i<0)return svg;const j=svg.indexOf('>',i);return `${svg.slice(0,j+1)}${content}${svg.slice(j+1)}`;}
 function modelToSheet(model={},o={}){const opt=sheetOptions(o),margin=o.margin??18,titleH=36;const rooms=model.rooms||model.floorPlan?.rooms||[];const maxX=Math.max(1,...rooms.map(r=>(+r.x||0)+(+r.width||0)),model.width||model.footprint?.width||1);const maxY=Math.max(1,...rooms.map(r=>(+r.y||0)+(+r.height||0)),model.depth||model.footprint?.depth||1);const body={x:margin,y:margin,width:opt.width-margin*2,height:opt.height-margin*2-titleH};const scale=Math.min(body.width/maxX,body.height/maxY);return{...opt,body,modelWidth:maxX,modelDepth:maxY,unitScale:scale,x:(v)=>body.x+(+v||0)*scale,y:(v)=>body.y+(+v||0)*scale,w:(v)=>(+v||0)*scale,h:(v)=>(+v||0)*scale};}
 class CadLayerGenerator{constructor(){this.layers=[];} add(name,content='',meta={}){this.layers.push({name,content,meta});return this;} group(){return this.layers.map(l=>`<g id="${esc(l.name)}" data-layer-name="${esc(l.name)}" data-discipline="${esc(l.meta.discipline||'')}" data-print="${l.meta.print!==false}">${l.content}</g>`).join('');}}
 class DimensionEngine{generate(model={},ctx=modelToSheet(model)){const rooms=model.rooms||[];const dims=[];dims.push(p.drawDimensionLine({id:'dimension-overall-x',x1:ctx.body.x,y1:ctx.body.y+ctx.body.height+8,x2:ctx.body.x+ctx.w(ctx.modelWidth),y2:ctx.body.y+ctx.body.height+8,text:`${Math.round(ctx.modelWidth)}mm`}));dims.push(p.drawDimensionLine({id:'dimension-overall-y',x1:ctx.body.x-8,y1:ctx.body.y,x2:ctx.body.x-8,y2:ctx.body.y+ctx.h(ctx.modelDepth),text:`${Math.round(ctx.modelDepth)}mm`,transform:`rotate(-90 ${ctx.body.x-8} ${ctx.body.y})`}));rooms.slice(0,20).forEach((r,i)=>dims.push(p.drawDimensionLine({id:`dimension-room-${esc(r.id||r.roomId||i)}`,x1:ctx.x(r.x),y1:ctx.y(r.y)+ctx.h(r.height)+3,x2:ctx.x(r.x)+ctx.w(r.width),y2:ctx.y(r.y)+ctx.h(r.height)+3,text:Math.round(+r.width||0)})));return dims.join('');}}
 class TextPlacementEngine{place(labels=[],opts={}){let y=opts.y??24;return labels.map((l,i)=>({id:l.id||`text-${i+1}`,x:l.x??(opts.x??24),y:l.y??(y+=5),text:l.text||l.name||'',width:(l.text||l.name||'').length*(opts.fontSize||2.5)*.6,height:opts.fontSize||2.5}));} render(labels=[]){return labels.map(l=>p.drawText({id:l.id,x:l.x,y:l.y,text:l.text,className:l.className||'text-note',fontSize:l.fontSize||2.5,textAnchor:l.textAnchor||'start'})).join('');}}
 class LeaderLineEngine{render(items=[]){return items.map((it,i)=>p.drawGroup({id:it.id||`leader-${i+1}`,className:'leader-line',children:[p.drawLine({x1:it.x1,y1:it.y1,x2:it.x2,y2:it.y2,className:'line-thin'}),p.drawText({x:it.x2+2,y:it.y2,text:it.text||'',className:'text-note',fontSize:2.5,textAnchor:'start'})]})).join('');}}
 class EquipmentSymbolRenderer{render(items=[],ctx){return items.map((e,i)=>p.drawGroup({id:e.id||`equipment-symbol-${i+1}`,className:`equipment-symbol ${e.type||'device'}`,children:[p.drawRect({x:ctx?ctx.x(e.x):e.x,y:ctx?ctx.y(e.y):e.y,width:e.width||8,height:e.height||6,fill:'none',className:'line-medium'}),p.drawText({x:(ctx?ctx.x(e.x):e.x)+(e.width||8)/2,y:(ctx?ctx.y(e.y):e.y)+(e.height||6)/2,text:e.code||e.type||'EQ',fontSize:2.2,className:'text-note'})]})).join('');}}
 class PipeRenderer{render(routes=[]){return routes.map((r,i)=>p.drawPolyline({id:r.id||`pipe-${i+1}`,points:r.points||[],className:'pipe-line line-medium',strokeWidth:r.strokeWidth||.3,fill:'none'})).join('');}}
 class DuctRenderer{render(routes=[]){return routes.map((r,i)=>p.drawPolyline({id:r.id||`duct-${i+1}`,points:r.points||[],className:'duct-line line-heavy',strokeWidth:r.strokeWidth||.5,fill:'none'})).join('');}}
 class CableRenderer{render(routes=[]){return routes.map((r,i)=>p.drawPolyline({id:r.id||`cable-${i+1}`,points:r.points||[],className:'cable-line line-thin line-dashed',strokeWidth:r.strokeWidth||.15,fill:'none'})).join('');}}
 class LegendGenerator{render(items=[],o={}){const x=o.x??24,y=o.y??220;const rows=[p.drawText({id:'legend-title',x,y,text:'凡例',className:'text-title',fontSize:3,textAnchor:'start'})];(items.length?items:[{code:'AHU',name:'空調機'},{code:'P',name:'ポンプ'},{code:'LP',name:'分電盤'}]).forEach((it,i)=>rows.push(p.drawText({id:`legend-item-${i+1}`,x,y:y+6+i*5,text:`${it.code} ${it.name}`,className:'text-legend',fontSize:2.5,textAnchor:'start'})));return p.drawGroup({id:'legend',className:'legend',children:rows});}}
 class TitleBlockGenerator{render(o={}){return p.drawTitleBlock({...sheetOptions(o),x:o.x??250,y:o.y??258});}}
 class DrawingQualityChecker{check(svg,json={}){const r=qc.validateDrawingQuality?qc.validateDrawingQuality(svg,json):{checks:{},warnings:[]};const required={hasLegend:/id="legend/.test(svg),hasTitleBlock:/title-block/.test(svg),hasScale:/S=1\//.test(svg),hasNorth:/north-arrow/.test(svg),textCollisions:!(r.warnings||[]).includes('textCollisions'),dimensionOverlap:!/(dimension-[^" ]+).*\1/.test(svg),missingSymbols:!/data-symbol-missing="true"/.test(svg)};return{passed:r.passed!==false&&Object.values(required).every(Boolean),checks:{...r.checks,...required},warnings:[...(r.warnings||[]),...Object.entries(required).filter(([,v])=>!v).map(([k])=>k)]};}}
 class SvgRenderer{render(model={},o={}){const kind=o.drawingType||o.discipline||'equipment',d=DISCIPLINES[kind]||DISCIPLINES.equipment,ctx=modelToSheet(model,{...o,title:o.title||d.title,drawingNumber:o.drawingNumber||d.no});let svg=(base.createSvgDocument?base.createSvgDocument(ctx):`<svg></svg>`);const rooms=(model.rooms||[]).map((r,i)=>p.drawGroup({id:`room-${esc(r.id||r.roomId||i)}`,children:[p.drawRect({x:ctx.x(r.x),y:ctx.y(r.y),width:ctx.w(r.width),height:ctx.h(r.height),fill:'none',className:'line-medium wall-room'}),p.drawText({id:`room-label-${esc(r.id||r.roomId||i)}`,x:ctx.x(r.x)+ctx.w(r.width)/2,y:ctx.y(r.y)+ctx.h(r.height)/2,text:r.name||r.roomName||'',className:'text-room',fontSize:3.5})]})).join('');const equipment=new EquipmentSymbolRenderer().render(model.equipment||model.equipmentItems||[],ctx);const routes=[new PipeRenderer().render(model.pipes||[]),new DuctRenderer().render(model.ducts||[]),new CableRenderer().render(model.cables||[])].join('');svg=inject(svg,'Layer01_Architecture',rooms+p.drawNorthArrow({x:ctx.width-38,y:34})+p.drawScaleBar({x:24,y:ctx.height-34,text:ctx.scale}));svg=inject(svg,d.layer,equipment+routes);svg=inject(svg,'Layer03_Dimensions',new DimensionEngine().generate(model,ctx));svg=inject(svg,'Layer07_Print',new LegendGenerator().render(model.legend,{x:ctx.width-116,y:52}));return svg;} renderJson(model={},o={}){const svg=this.render(model,o);return{format:'drawing-json',sheet:sheetOptions(o),svg,previewPng:null,pdf:null,dxf:null,printData:{media:o.sheetSize||'A3',scale:o.scale||'S=1/100'}};}}
 const api={SvgRenderer,CadLayerGenerator,DimensionEngine,TextPlacementEngine,LeaderLineEngine,EquipmentSymbolRenderer,PipeRenderer,DuctRenderer,CableRenderer,LegendGenerator,TitleBlockGenerator,DrawingQualityChecker,modelToSheet,sheetOptions};
 if(typeof module!=='undefined')module.exports=api; root.cadDrawingEngine=api;
})(typeof window!=='undefined'?window:globalThis);
