(function(root){
 const p=root.svgPrimitives||(typeof require==='function'?require('./svgPrimitives'):{});
 const esc=(v)=>String(v??'item').replace(/[^A-Za-z0-9_-]/g,'-');
 const safe=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
 function txFor(plan={}){const xs=[...(plan.rooms||[]),...(plan.equipmentSpaces||[]),...(plan.shafts||[])];let w=64000,h=40000;xs.forEach(e=>{w=Math.max(w,safe(e.x)+safe(e.width));h=Math.max(h,safe(e.y)+safe(e.height));});const s=Math.min(270/w,190/h);return{width:w,depth:h,s,ox:55+(270-w*s)/2,oy:55+(190-h*s)/2,x:v=>55+(270-w*s)/2+safe(v)*s,y:v=>55+(190-h*s)/2+safe(v)*s,l:v=>safe(v)*s};}
 function shaft(plan,type){return(plan.shafts||[]).find(s=>s.shaftType===type)||(plan.equipmentSpaces||[]).find(s=>String(s.name).includes(type));}
 function center(e,t){return e?{x:t.x(safe(e.x)+safe(e.width)/2),y:t.y(safe(e.y)+safe(e.height)/2)}:{x:t.x(t.width*.82),y:t.y(t.depth*.45)};}
 function route(id,from,to,offset=0,cls='eq-line-main',sw=.35,color='#000'){const midX=(from.x+to.x)/2+offset;return p.drawPolyline({id,points:[[from.x,from.y],[midX,from.y],[midX,to.y],[to.x,to.y]],className:cls,stroke:color,strokeWidth:sw,fill:'none'});}
 function useSymbol(id,symbol,x,y,w=8,h=6,color='#000'){return `<use id="${id}" href="#eqsym-${symbol}" x="${x-w/2}" y="${y-h/2}" width="${w}" height="${h}" color="${color}" class="equipment-symbol"/>`;}
 function arrow(id,x,y,color='#000'){return `<path id="${id}" d="M ${x-3} ${y-2} L ${x+3} ${y} L ${x-3} ${y+2}" fill="none" stroke="${color}" stroke-width="0.15"/>`;}
 function css(color){return `<style id="equipment-print-style"><![CDATA[@page{size:A3 landscape;margin:0}.eq-line-main{fill:none;stroke-width:.35;stroke-linecap:square;stroke-linejoin:miter}.eq-line-branch{fill:none;stroke-width:.20;stroke-dasharray:4 1.5}.eq-duct-main{fill:none;stroke-width:.40}.eq-duct-branch{fill:none;stroke-width:.25;stroke-dasharray:5 2}.eq-wire-main{fill:none;stroke-width:.35}.eq-wire-branch{fill:none;stroke-width:.18;stroke-dasharray:3 1.5}.equipment-symbol{stroke-width:.25}.leader-line{stroke-width:.15}.equipment-color{stroke:${color};color:${color}}@media print{.no-print{display:none!important}svg{background:#fff}.equipment-color,.eq-line-main,.eq-line-branch,.eq-duct-main,.eq-duct-branch,.eq-wire-main,.eq-wire-branch,.equipment-symbol{stroke:#000!important;color:#000!important}.screen-color-fill{fill:#000!important}}]]></style>`}
 function systems(equipment,keys){const e=equipment&&equipment.equipment?equipment.equipment:equipment||{};return keys.flatMap(k=>(e[k]?.systems||[]));}
 function table(rows){const out=[p.drawText({id:'equipment-schedule-title',x:300,y:121,text:'機器表',className:'text-title',fontSize:3,textAnchor:'start'})];['機器番号','機器名称','設置場所','能力','電源','備考'].forEach((h,i)=>out.push(p.drawText({id:`equipment-schedule-h-${i}`,x:300+i*18,y:127,text:h,className:'text-legend',fontSize:1.9,textAnchor:'start'})));rows.slice(0,6).forEach((r,ri)=>['no','name','location','capacity','power','note'].forEach((k,i)=>out.push(p.drawText({id:`equipment-schedule-${ri}-${i}`,x:300+i*18,y:132+ri*5,text:r[k]||'-',className:'text-legend',fontSize:1.8,textAnchor:'start'}))));return out.join('');}
 const api={p,esc,txFor,shaft,center,route,useSymbol,arrow,css,systems,table}; if(typeof module!=='undefined')module.exports=api; root.equipmentDrawingShared=api;
})(typeof window!=='undefined'?window:globalThis);
