(function(root){
 const arch=root.architecturalDrawingRenderer||(typeof require==='function'?require('./architecturalDrawingRenderer'):{});
 const sym=root.equipmentSymbols||(typeof require==='function'?require('./equipmentSymbols'):{});
 const h=root.equipmentDrawingShared||(typeof require==='function'?require('./equipmentDrawingShared'):{});
 const hvac=root.hvacDrawingRenderer||(typeof require==='function'?require('./hvacDrawingRenderer'):{});
 const plumbing=root.plumbingDrawingRenderer||(typeof require==='function'?require('./plumbingDrawingRenderer'):{});
 const electrical=root.electricalDrawingRenderer||(typeof require==='function'?require('./electricalDrawingRenderer'):{});
 const titles={hvac:'空調・換気設備平面図',plumbing:'給排水衛生設備平面図',electrical:'電気設備平面図'};
 const nums={hvac:'M-101',plumbing:'P-101',electrical:'E-101'};
 const colors={hvac:'#0066cc',plumbing:'#008040',electrical:'#cc0000'};
 function add(svg,layer,content){const n=`<g id="${layer}" data-layer-name="${layer}"`;const i=svg.indexOf(n);if(i<0)return svg;const j=svg.indexOf('>',i);return `${svg.slice(0,j+1)}${content}${svg.slice(j+1)}`;}
 function replaceDefs(svg,content){return svg.replace('</defs>',`${content}</defs>`);}
 function duplicateIds(svg){const seen=new Set();return svg.replace(/id="([^"]+)"/g,(m,id)=>{if(!seen.has(id)){seen.add(id);return m;}let n=2;while(seen.has(`${id}-${n}`))n++;seen.add(`${id}-${n}`);return `id="${id}-${n}"`;});}
 function legend(discipline){const items={hvac:[['AHU','空調機','AHU','実線','空調'],['FD','防火ダンパー','FD','破線','防火区画'],['D','ダクト','DUCT','太線','給排気']],plumbing:[['P','ポンプ','P','実線','給水'],['V','弁','V','実線','止水'],['SP','スプリンクラー','SP','破線','消火']],electrical:[['TR','変圧器','TR','実線','受変電'],['LP','分電盤','LP','実線','照明'],['C','コンセント','C','破線','電灯']]}[discipline]||[];const out=[h.p.drawText({id:'equipment-legend-title',x:300,y:55,text:'凡例',className:'text-title',fontSize:3,textAnchor:'start'})];items.forEach((it,i)=>{out.push(h.p.drawText({id:`equipment-legend-${i}`,x:300,y:62+i*5,text:`${it[0]} ${it[1]} / 略号:${it[2]} / 線種:${it[3]} / 用途:${it[4]}`,className:'text-legend',fontSize:2,textAnchor:'start'}));});return out.join('');}
 function schedule(equipment,discipline){const keys={hvac:['hvac','ventilation'],plumbing:['waterSupply','hotWater','drainage','fireSafety'],electrical:['electrical','receivingTransformer','emergencyPower','lighting','buildingManagement']}[discipline];return h.table(h.systems(equipment,keys).map((s,i)=>({no:`${discipline[0].toUpperCase()}-${i+1}`,name:s.name,location:s.location,capacity:s.capacity?`${s.capacity.value}${s.capacity.unit}`:'-',power:discipline==='electrical'?'三相/単相':'-',note:(s.requirements||[])[0]})));}
 function renderEquipmentDrawing({drawing,equipment,discipline,options={}}={}){try{if(!['hvac','plumbing','electrical'].includes(discipline))throw new Error('選択設備区分が無効です。');if(!drawing)throw new Error('選択階がありません。');if(!equipment)throw new Error('設備データがありません。');const missing=['EPS','PS','DS'].filter(t=>!(drawing.shafts||[]).some(s=>s.shaftType===t));let svg=arch.renderArchitecturalDrawing(drawing,{kind:'floor',title:titles[discipline],drawingNumber:nums[discipline],scale:drawing.scale});const color=options.screenColorMode&&!options.monochrome?colors[discipline]:'#000';svg=replaceDefs(svg,(sym.createEquipmentSymbolDefinitions?sym.createEquipmentSymbolDefinitions():'')+h.css(color));const renderer={hvac:hvac.renderHvacDrawing,plumbing:plumbing.renderPlumbingDrawing,electrical:electrical.renderElectricalDrawing}[discipline];const result=renderer({floorPlan:drawing,equipment,options:{...options,color}});svg=add(svg,'Layer04_Equipment',`<g id="equipment-${discipline}" class="equipment-color">${result.equipment||''}</g>`);svg=add(svg,'Layer05_Text',`${result.text||''}${missing.length?h.p.drawText({id:'equipment-warning-missing-shaft',x:55,y:250,text:`注意：${missing.join('、')}がありません。`,className:'text-note',fontSize:2.5,textAnchor:'start'}):''}`);svg=add(svg,'Layer07_Print',legend(discipline)+schedule(equipment,discipline));svg=svg.replace(/>[^<]*(平面図|配置図)?<\/text>/,`>${titles[discipline]}</text>`).replace(/floor-plan-[^<]+<\/text>/,`${nums[discipline]}</text>`);return duplicateIds(svg);}catch(error){let svg=arch.renderArchitecturalDrawing(drawing||{floorId:'error',floorName:'設備図生成エラー',rooms:[]},{kind:'floor'});return add(svg,'Layer05_Text',h.p.drawText({id:'equipment-renderer-error',x:30,y:40,text:`設備図生成失敗: ${error.message||error}`,className:'text-note',fontSize:3,textAnchor:'start'}));}}
 const api={renderEquipmentDrawing}; if(typeof module!=='undefined')module.exports=api; root.equipmentDrawingRenderer=api;
})(typeof window!=='undefined'?window:globalThis);
