(function (root) {
  const lib = root.architecturalPatternLibrary || (typeof require === 'function' ? require('./architecturalPatternLibrary') : {});
  const arr = (v) => Array.isArray(v) ? v : [];
  const clone = (v) => JSON.parse(JSON.stringify(v || {}));
  const n = (v, d = 0) => Number.isFinite(Number(v)) ? Number(v) : d;
  const rect = (id, name, x, y, width, height, extra = {}) => ({ id, roomId: id, name, x, y, width, height, area: Math.round(width * height / 100000) / 10, architecturalPattern: true, ...extra });
  function bounds(d = {}) { const fp = d.footprint || {}; return arr(d.rooms).reduce((b, r) => ({ width: Math.max(b.width, n(r.x) + n(r.width)), depth: Math.max(b.depth, n(r.y) + n(r.height)) }), { width: n(fp.width, 50400), depth: n(fp.depth, 36000) }); }
  function uniq(items) { return [...new Map(items.filter(Boolean).map((x) => [x.id || x.roomId || `${x.name}-${x.x}-${x.y}`, x])).values()]; }
  function addRooms(d, names, prefix) { const b = bounds(d); const have = (name) => arr(d.rooms).some((r) => String(r.name || '').includes(name.replace(/列/g, ''))); const width = Math.max(4800, Math.floor(b.width / Math.max(4, names.length))); const y = Math.max(0, b.depth - 9000); const rooms = names.filter((name) => !/PS|EPS|EV|廊下/.test(name) && !have(name)).map((name, i) => rect(`AP-${prefix}-${i + 1}`, name, 1200 + i * width, y, Math.min(width - 600, 7200), 6000, { zone: prefix })); return { ...d, rooms: uniq([...arr(d.rooms), ...rooms]) }; }
  const FloorCompositionPlanner = { plan(building = {}, floorPlans = [], pattern = {}) { return arr(pattern.composition).map((c) => ({ ...c, source: 'ArchitecturalPatternLibrary', applicableFloorIds: String(c.floorId).includes('-') ? String(c.floorId).split('-') : [String(c.floorId)] })); } };
  const TypicalFloorGenerator = { generate(drawing = {}, pattern = {}) { const d = clone(drawing); const floorText = [d.floorId, d.floorName].join(' '); const isTypical = /客室|基準|病棟|普通教室|執務|3|4|5|6|7|8|9|10/.test(floorText); return isTypical ? addRooms(d, pattern.typical || [], pattern.use || 'facility') : d; } };
  function generator(use) { return { generate(drawing, building, pattern) { const d = TypicalFloorGenerator.generate(drawing, pattern); const floor = [d.floorId, d.floorName].join(' '); const comp = arr(pattern.composition).find((c) => String(c.floorId) === String(d.floorId) || String(c.role).includes(d.floorName || '') || (String(c.floorId).includes('-') && /[3-9]|10/.test(String(d.floorId)))); const names = comp?.rooms || pattern.zones || []; return addRooms({ ...d, floorCompositionRole: comp?.role || pattern.label }, names, use); } }; }
  const HotelPatternGenerator = generator('hotel'), HospitalPatternGenerator = generator('hospital'), SchoolPatternGenerator = generator('school'), OfficePatternGenerator = generator('office'), FacilityPatternGenerator = generator('facility');
  const PatternConsistencyChecker = { check(d = {}, pattern = {}) { const rooms = arr(d.rooms).map((r) => r.name || '').join(' '); const checks = { 用途: !!pattern.use, 階構成: !!d.floorCompositionRole || arr(d.floorComposition).length > 0, 設備計画: ['PS','EPS'].every((s) => arr(d.shafts).some((x) => String(x.name || x.shaftType).includes(s))), 動線: arr(d.circulationRoutes).length > 0 || /廊下/.test(rooms), コア: arr(d.elevators).length > 0 || /EV/.test(rooms), 設備スペース: arr(d.equipmentSpaces).length > 0 || /機械|PS|EPS/.test(rooms) }; return { checks, warnings: Object.entries(checks).filter(([, ok]) => !ok).map(([k]) => `${k}の建築パターン整合を確認してください。`) }; } };
  const ArchitecturalPatternChecker = { check(d = {}, pattern = {}) { const c = PatternConsistencyChecker.check(d, pattern); const exam = !!d.architecturalPatternEngine && arr(d.rooms).some((r) => r.architecturalPattern); const checks = { ...c.checks, 平面構成: arr(d.rooms).length >= 3, 試験適合: exam }; const score = Math.round(Object.values(checks).filter(Boolean).length / Object.keys(checks).length * 100); return { score, checks, warnings: score < 95 ? [`Architectural pattern score is ${score}; 95点未満です。`, ...c.warnings] : c.warnings }; } };
  function enhance({ building = {}, floorPlans = [], drawing = {} } = {}) { const pattern = (lib.PatternSelector || lib).select ? (lib.PatternSelector || lib).select(building) : lib.selectPattern(building); const planner = FloorCompositionPlanner.plan(building, floorPlans, pattern); let d = clone(drawing.floorPlan || drawing || arr(floorPlans)[0] || {}); const gen = { hotel: HotelPatternGenerator, hospital: HospitalPatternGenerator, school: SchoolPatternGenerator, office: OfficePatternGenerator }[pattern.use] || FacilityPatternGenerator; d = gen.generate(d, building, pattern); d.floorComposition = planner; d.architecturalPatternEngine = 'ArchitecturalPatternEngine'; d.patternMetadata = { buildingGeneratorCompatible: true, buildingPreview: true, blankDrawing: true, commonQuestionCrop: true, equipmentGeneratorCompatible: true, svgPdf: true, apiCompatible: true, order: 'RoomLayoutEngine→ExamCadQualityEngine→BuildingRealismEngine→ArchitecturalPatternEngine→CropEngine→ExamDrawingTemplateEngine' }; const q = ArchitecturalPatternChecker.check(d, pattern); return { drawing: d, pattern, score: q.score, warnings: q.warnings, checks: q.checks }; }
  const api = { enhance, ArchitecturalPatternEngine: { enhance }, PatternSelector: lib.PatternSelector, HotelPatternGenerator, HospitalPatternGenerator, SchoolPatternGenerator, OfficePatternGenerator, FacilityPatternGenerator, FloorCompositionPlanner, TypicalFloorGenerator, PatternConsistencyChecker, ArchitecturalPatternChecker };
  if (typeof module !== 'undefined') module.exports = api;
  root.architecturalPatternEngine = api;
})(typeof window !== 'undefined' ? window : globalThis);
