(function(root){
 const box=(e)=>e.bbox||{x:e.x||0,y:e.y||0,width:e.width||((String(e.text||'').length||1)*(e.fontSize||3)*.6),height:e.height||(e.fontSize||3)};
 const hit=(a,b)=>{a=box(a);b=box(b);return a.x<b.x+b.width&&a.x+a.width>b.x&&a.y<b.y+b.height&&a.y+a.height>b.y;};
 function calculateIntersectionArea(a,b){a=box(a);b=box(b);const x=Math.max(0,Math.min(a.x+a.width,b.x+b.width)-Math.max(a.x,b.x));const y=Math.max(0,Math.min(a.y+a.height,b.y+b.height)-Math.max(a.y,b.y));return x*y;}
 function hasAreaOverlap(a,b,tolerance=1){return calculateIntersectionArea(a,b)>tolerance;}
 function detectCollisions(elements=[]){const collisions=[];for(let i=0;i<elements.length;i++)for(let j=i+1;j<elements.length;j++)if(hit(elements[i],elements[j]))collisions.push({a:elements[i].id,b:elements[j].id,type:`${elements[i].type||'element'}-${elements[j].type||'element'}`});return {collisions,warnings:collisions.map(c=>`collision: ${c.a}/${c.b}`)};}
 function resolveTextCollisions(elements=[]){const out=elements.map(e=>({...e}));const warnings=[];for(let pass=0;pass<8;pass++){let moved=false;for(let i=0;i<out.length;i++)for(let j=i+1;j<out.length;j++)if((out[i].type==='text'||out[j].type==='text')&&hit(out[i],out[j])){const t=out[j].type==='text'?out[j]:out[i];t.y=(t.y||0)+(t.fontSize||3)+1;moved=true;}} const unresolved=detectCollisions(out).collisions.filter(c=>c.type.includes('text')); unresolved.forEach(c=>warnings.push(`unresolved text collision: ${c.a}/${c.b}`)); return {elements:out,warnings};}
 function validateSheetLayout(sheet={}){const elements=Object.entries(sheet.regions||{}).filter(([,v])=>v&&v.width).map(([id,v])=>({id,type:id,...v}));const r=detectCollisions(elements);const warnings=[...(sheet.warnings||[]),...r.warnings];return {valid:warnings.length===0,warnings,collisions:r.collisions};}
 function validateSpatialConflicts(floorPlan={}){const rooms=floorPlan.rooms||[];const conflicts=[];const significant=(a,b)=>hasAreaOverlap(a,b,1); for(let i=0;i<rooms.length;i++)for(let j=i+1;j<rooms.length;j++){const a=rooms[i],b=rooms[j]; if(!significant(a,b))continue; const pair=[a.zone,b.zone].sort().join('-'); const isCritical=/guest/.test(pair)&&/(core|corridor|shaft|stair)/.test(pair); const isRoomRoom=!['corridor','safety'].includes(a.zone)&&!['corridor','safety'].includes(b.zone)&&a.zone!=='core'&&b.zone!=='core'&&a.zone!=='shaft'&&b.zone!=='shaft'; if(isCritical||isRoomRoom)conflicts.push({a:a.roomId,b:b.roomId,type:isCritical?'critical-reserved-overlap':'room-overlap',area:calculateIntersectionArea(a,b)});} const graph=floorPlan.circulationGraph||{nodes:[],edges:[]}; const connected=new Set((graph.edges||[]).flatMap(e=>[e.from,e.to])); const isolatedRooms=rooms.filter(r=>!['safety'].includes(r.zone)&&!(connected.has(r.roomId)||connected.has(r.id))).map(r=>r.roomId); const doorlessRooms=rooms.filter(r=>!['corridor','safety','shaft'].includes(r.zone)&&!(r.door||r.doors||r.zone==='core'||r.zone==='stair')).map(r=>r.roomId); return {isValid:conflicts.length===0&&isolatedRooms.length===0&&doorlessRooms.length===0,conflicts,isolatedRooms,doorlessRooms,metrics:{overlapCount:conflicts.length,coreConflictCount:conflicts.filter(c=>/CORE|EV|ST|EPS|PS|DS/.test(`${c.a}${c.b}`)).length,corridorConflictCount:conflicts.filter(c=>/COR/.test(`${c.a}${c.b}`)).length,shaftConflictCount:conflicts.filter(c=>/EPS|PS|DS/.test(`${c.a}${c.b}`)).length,isolatedRoomCount:isolatedRooms.length,doorlessRoomCount:doorlessRooms.length,unconnectedCorridorCount:(floorPlan.corridors||[]).filter(c=>!(connected.has(c.id)||connected.has(c.corridorId))).length,egressInvalidCount:(floorPlan.egressRoutes||[]).length>=2?0:1}};}
 function removeOverlappingRooms(floorPlan={}){const v=validateSpatialConflicts(floorPlan);const bad=new Set(v.conflicts.filter(c=>c.type==='critical-reserved-overlap').flatMap(c=>[c.a,c.b]));return {...floorPlan,rooms:(floorPlan.rooms||[]).filter(r=>!(bad.has(r.roomId)&&r.zone==='guest'))};}
 function repackRooms(floorPlan={}){return removeOverlappingRooms(floorPlan);}
 const api={detectCollisions,resolveTextCollisions,validateSheetLayout,calculateIntersectionArea,hasAreaOverlap,validateSpatialConflicts,removeOverlappingRooms,repackRooms}; if(typeof module!=='undefined')module.exports=api; root.collisionDetector=api;
})(typeof window!=='undefined'?window:globalThis);
