(function(root){
 function area(items){return (items||[]).reduce((s,r)=>s+Math.max(0,(+r.width||0)*(+r.height||0)),0)}
 function num(v,d=0){return Number.isFinite(Number(v))?Number(v):d}
 function attr(svg,name){const m=String(svg||'').match(new RegExp(`${name}="([^"]+)"`)); return m?Number(m[1]):NaN}
 function count(re,svg){return (String(svg||'').match(re)||[]).length}
 function unique(re,svg){return new Set([...String(svg||'').matchAll(re)].map(m=>m[1])).size}
 function minFont(svg){const vals=[...String(svg||'').matchAll(/font-size="([0-9.]+)"/g)].map(m=>Number(m[1])).filter(Number.isFinite); return vals.length?Math.min(...vals):2.5}
 function svgMetrics(svg){return {paperUsageRatio:attr(svg,'data-paper-usage-ratio'),generatedGuestRoomCount:attr(svg,'data-generated-guest-rooms'),svgGuestRoomCount:count(/class="[^"]*guest-room/g,svg),furnishedGuestRoomCount:unique(/class="[^"]*furniture[^"]*"[^>]*data-room-ref="([^"]+)"/g,svg),roomNameDrawnCount:count(/id="room-label-/g,svg),roomAreaDrawnCount:count(/id="room-area-/g,svg),furnitureCount:count(/class="[^"]*furniture/g,svg),dimensionCount:count(/id="dimension-/g,svg),minTextSize:minFont(svg)};}
 function calculateFloorPlanQualityMetrics({floorPlan={},svg='',building={},plan={}}={}){const fp=floorPlan.footprint||{width:64000,depth:40000}; const rooms=floorPlan.rooms||[]; const guest=rooms.filter(r=>r.zone==='guest'); const roomArea=area(rooms.filter(r=>!['outside','safety'].includes(r.zone))); const actual=svgMetrics(svg); const rawUsage=roomArea/(fp.width*fp.depth||1); const paperUsageRatio=Number((Number.isFinite(actual.paperUsageRatio)?actual.paperUsageRatio:num(floorPlan.paperUsageRatio,0)).toFixed(3)); const guestRoomCount=guest.length; const svgGuestRoomCount=actual.svgGuestRoomCount||0; const furnitureCount=actual.furnitureCount||(floorPlan.furniture||[]).length; const dimensionCount=actual.dimensionCount||(floorPlan.dimensions||[]).length; const roomUsageRatio=Number(Math.min(.98,rawUsage).toFixed(3)); return {paperUsageRatio,roomUsageRatio,guestRoomCount,generatedGuestRoomCount:guestRoomCount,svgGuestRoomCount,furnishedGuestRoomCount:actual.furnishedGuestRoomCount,roomNameDrawnCount:actual.roomNameDrawnCount,roomAreaDrawnCount:actual.roomAreaDrawnCount,furnitureCount,dimensionCount,shaftCount:(floorPlan.shafts||[]).length+rooms.filter(r=>/EPS|PS|DS/.test(r.name||r.roomId||'')).length,coreAreaRatio:Number((area(rooms.filter(r=>r.zone==='core'))/(fp.width*fp.depth||1)).toFixed(3)),textCollisionCount:floorPlan.textCollisionCount||0,unusedAreaRatio:Number(Math.max(0,1-Math.min(.98,rawUsage)).toFixed(3)),egressRouteCount:(floorPlan.egressRoutes||[]).length,minTextSize:actual.minTextSize};}
 function validateFloorPlanQuality(args={}){const m=calculateFloorPlanQualityMetrics(args); const f=args.floorPlan||{}; const errors=[],warnings=[],checks=[]; const add=(id,ok,msg=id)=>{checks.push({id,ok}); if(!ok)errors.push(msg)}; add('paper-usage',m.paperUsageRatio>=.72&&m.paperUsageRatio<=.80,`paper-usage:${m.paperUsageRatio}`); add('room-usage',f.floorId==='1'?m.roomUsageRatio>=.75:f.floorId==='TYP'?m.roomUsageRatio>=.80:true,`room-usage:${m.roomUsageRatio}`); if(f.floorId==='TYP'){add('guest-count',m.guestRoomCount>=24&&m.guestRoomCount<=36,`guest-count:${m.guestRoomCount}`); add('svg-guest-count',m.svgGuestRoomCount===m.guestRoomCount,`svg-guest-count:${m.svgGuestRoomCount}/${m.guestRoomCount}`); add('unused-area',m.unusedAreaRatio<=.15,`unused-area:${m.unusedAreaRatio}`); add('furnished-rooms',m.furnishedGuestRoomCount===m.guestRoomCount,`furnished-rooms:${m.furnishedGuestRoomCount}/${m.guestRoomCount}`);} add('stairs', (f.stairs||[]).length>=2); add('ev', (f.elevators||[]).length>=2); add('shafts', m.shaftCount>=3); add('furniture', f.floorId==='TYP'?m.furnitureCount>=m.guestRoomCount*8:true); add('dimensions', m.dimensionCount>=8); add('egress', m.egressRouteCount>=2||['RF','PH'].includes(f.floorId)); add('legend-title', /legend|凡例/.test(args.svg||'') && /title-block/.test(args.svg||'')); add('min-text-size',m.minTextSize>=2.2,`min-text-size:${m.minTextSize}`); add('text-collision', m.textCollisionCount<=6); return {isValid:errors.length===0,errors,warnings,checks,metrics:m};}
 const api={calculateFloorPlanQualityMetrics,validateFloorPlanQuality,svgMetrics}; if(typeof module!=='undefined')module.exports=api; root.floorPlanQualityMetrics=api;
})(typeof window!=='undefined'?window:globalThis);
