function makeIdFactory() { const used = new Set(); return (base) => { let id = base; let n = 2; while (used.has(id)) id = `${base}-${n++}`; used.add(id); return id; }; }
const normalize = (v) => String(v || '').toLowerCase();
const has = (type, name) => normalize(type).includes(name);
function enabledAreas(answerType) {
  const t = normalize(answerType);
  return { description: has(t, 'description'), calculation: has(t, 'calculation'), selection: has(t, 'selection'), diagram: has(t, 'diagram'), unit: has(t, 'calculation'), rationale: has(t, 'calculation') };
}
function field(id, label, kind, extra = {}) { return { id, label, kind, enabled: true, ...extra }; }
function commonFields(exam, makeId) { return {
  examName: exam?.cover?.examName || '建築設備士試験 第二次試験（設計製図）', mockLabel: exam?.cover?.mockLabel || '模擬試験', designTaskName: exam?.projectTitle || exam?.cover?.designTaskName || '',
  examineeNumber: field(makeId('answer-common-examinee-number'), '受験番号', 'text', { width: '45mm' }), name: field(makeId('answer-common-name'), '氏名', 'text', { width: '60mm' }), sheetNumber: field(makeId('answer-common-sheet-number'), '答案用紙番号', 'text'), selectedDiscipline: field(makeId('answer-common-selected-discipline'), '選択設備区分', 'checkbox'), pageNumber: field(makeId('answer-common-page-number'), 'ページ番号', 'text'), scorerArea: field(makeId('answer-common-scorer'), '採点者記入欄', 'scorer'), notices: field(makeId('answer-common-notices'), '注意事項欄', 'notice', { text: '模範解答は含まれていません。黒鉛筆等で記入・作図してください。' })
}; }
function questionBlock(q, sheetType, prefix, makeId) { const en = enabledAreas(q.answerType); const base = `answer-${prefix}${String(q.number || q.questionId).replace(/[^a-z0-9]/gi, '').toLowerCase()}`; const areas = {
  description: field(makeId(`${base}-description`), '記述欄', 'description', { enabled: en.description }), calculation: field(makeId(`${base}-calculation`), '計算欄', 'calculation', { enabled: en.calculation }), selection: field(makeId(`${base}-selection`), '選択欄', 'selection', { enabled: en.selection }), diagram: field(makeId(`${base}-diagram`), '簡易図示欄', 'diagram', { enabled: en.diagram }), unit: field(makeId(`${base}-unit`), '単位記入欄', 'unit', { enabled: en.unit }), rationale: field(makeId(`${base}-rationale`), '算定根拠欄', 'rationale', { enabled: en.rationale })
}; return { questionId: q.questionId, number: q.number, title: q.title, answerType: q.answerType, answerSheetAreaId: q.answerSheetAreaId, drawingRequirements: q.drawingRequirements || [], areas, primaryAnswerSheetId: Object.values(areas).find((a) => a.enabled)?.id || areas.description.id, sheetType }; }
function selectionSheet(key, title, questions, makeId) { const sheetType = `${key}Sheet`; return { sheetId: makeId(`answer-${key}-sheet`), sheetType, title, size: 'A4-portrait', questions: (questions || []).map((q, i) => ({ ...questionBlock(q, sheetType, `${key}-q${i + 1}`, makeId), sectionTitle: `${q.questionId} ${q.title}` })) }; }
function commonDrawingSheet(questions, makeId) { return { sheetId: makeId('answer-sheet-4-common'), sheetType: 'answerSheet4', title: 'AnswerSheet4 共通問題答案用紙', size: 'A3-landscape', questions: (questions || []).map((q) => questionBlock(q, 'answerSheet4', q.questionId.toLowerCase(), makeId)), floorPlanArea: { id: makeId('answer-sheet-4-q03-fcu-piping'), blankPlanReference: true, includeModelAnswer: false, labels: ['Q03 客室階FCU配管図','FCU','冷水','温水','四管式','リバースリターン','ドレン','電動二方弁','立管 C CR H HR D'] }, detailArea: { id: makeId('answer-sheet-4-q04-toilet-piping'), labels: ['Q04 便所配管図','給水','給湯','排水','通気','ループ通気','PS接続','器具配管'] }, scheduleLegendArea: { id: makeId('answer-sheet-4-q05-lighting-design'), labels: ['Q05 照明設計','照明台数計算','照明配置','非常照明','誘導灯','感知器','非常放送','コンセント','スイッチ'] } }; }
function generateAnswerSheets({ exam, materials, drawings, options = {} } = {}) { const makeId = makeIdFactory(); const set = { answerSheetSetId: makeId(`answer-sheet-set-${exam?.examId || Date.now()}`), examId: exam?.examId || '', sheetSizePolicy: { written: 'A4-portrait', drawing: 'A3-landscape' }, commonFields: commonFields(exam, makeId), answerSheet1: selectionSheet('hvac', 'AnswerSheet1 空調選択問題答案用紙', exam?.selection?.hvac || exam?.electiveSections?.hvac, makeId), answerSheet2: selectionSheet('plumbing', 'AnswerSheet2 衛生選択問題答案用紙', exam?.selection?.plumbing || exam?.electiveSections?.plumbing, makeId), answerSheet3: selectionSheet('electrical', 'AnswerSheet3 電気選択問題答案用紙', exam?.selection?.electrical || exam?.electiveSections?.electrical, makeId), answerSheet4: commonDrawingSheet(exam?.common, makeId), metadata: { generator: 'answerSheetGenerator', schemaVersion: '1.0.0', material5Reference: (Array.isArray(materials) ? materials : materials?.materials || []).find((m) => m?.materialId === 'material-5')?.materialId || 'material-5', blankPlanReferences: (drawings?.blankPlans || []).map((p) => p.drawingId), includeBlankPlanBackground: !!options.includeBlankPlanBackground, noModelAnswer: true } };
 set.questionAnswerMap = [...set.answerSheet1.questions, ...set.answerSheet2.questions, ...set.answerSheet3.questions, ...set.answerSheet4.questions].map((q) => ({ questionId: q.questionId, answerSheetId: q.primaryAnswerSheetId, sheetType: q.sheetType, answerSheetAreaId: q.answerSheetAreaId })); return set; }
function collectIds(o, out = []) { if (!o || typeof o !== 'object') return out; if (o.id) out.push(o.id); if (o.sheetId) out.push(o.sheetId); Object.values(o).forEach((v) => Array.isArray(v) ? v.forEach((x) => collectIds(x, out)) : collectIds(v, out)); return out; }
function validateAnswerSheets(set, exam) { const errors = [], warnings = [], checks = []; const check = (name, ok, warn=false) => { checks.push({ name, ok: !!ok }); if (!ok) (warn ? warnings : errors).push(`${name}の検査に失敗しました。`); };
 check('AnswerSheet1', !!set?.answerSheet1); check('AnswerSheet2', !!set?.answerSheet2); check('AnswerSheet3', !!set?.answerSheet3); check('AnswerSheet4', !!set?.answerSheet4); ['answerSheet1','answerSheet2','answerSheet3'].forEach((k) => check(`${k}2問`, set?.[k]?.questions?.length === 2)); check('共通3問', set?.answerSheet4?.questions?.length === 3); const ids = collectIds(set); check('ID重複なし', ids.length === new Set(ids).size); const mapIds = new Set((set?.questionAnswerMap || []).map((m) => m.questionId)); const expected = [...Object.values(exam?.selection || exam?.electiveSections || {}).flat(), ...(exam?.common || [])]; expected.forEach((q) => check(`対応表:${q.questionId}`, mapIds.has(q.questionId))); check('Q03はAnswerSheet4', set?.questionAnswerMap?.find((m) => m.questionId === 'Q03')?.sheetType === 'answerSheet4'); check('Q04はAnswerSheet4', set?.questionAnswerMap?.find((m) => m.questionId === 'Q04')?.sheetType === 'answerSheet4'); check('Q05はAnswerSheet4', set?.questionAnswerMap?.find((m) => m.questionId === 'Q05')?.sheetType === 'answerSheet4'); const blocks = [...(set?.answerSheet1?.questions || []), ...(set?.answerSheet2?.questions || []), ...(set?.answerSheet3?.questions || []), ...(set?.answerSheet4?.questions || [])]; blocks.forEach((b) => { const en = enabledAreas(b.answerType); if (en.description) check(`${b.questionId}記述欄`, b.areas.description.enabled); if (en.calculation) check(`${b.questionId}計算欄`, b.areas.calculation.enabled && b.areas.unit.enabled); if (en.diagram) check(`${b.questionId}作図欄`, b.areas.diagram.enabled || b.sheetType === 'answerSheet4'); }); check('資料5整合', !!set?.metadata?.material5Reference, true); check('模範解答なし', !JSON.stringify(set || {}).includes('模範解答:') && !JSON.stringify(set || {}).includes('modelAnswer')); check('印刷用紙サイズ', set?.sheetSizePolicy?.written === 'A4-portrait' && set?.sheetSizePolicy?.drawing === 'A3-landscape'); return { isValid: errors.length === 0, errors, warnings, checks }; }

if (typeof module !== 'undefined') module.exports = { generateAnswerSheets, validateAnswerSheets };
if (typeof window !== 'undefined') { window.generateAnswerSheets = generateAnswerSheets; window.validateAnswerSheets = validateAnswerSheets; }
