function makeIdFactory() { const used = new Set(); return (base) => { let id = base; let n = 2; while (used.has(id)) id = `${base}-${n++}`; used.add(id); return id; }; }
const normalize = (v) => String(v || '').toLowerCase();
const has = (type, name) => normalize(type).includes(name);
function enabledAreas(answerType) {
  const t = normalize(answerType);
  return { description: has(t, 'description'), calculation: has(t, 'calculation'), selection: has(t, 'selection'), diagram: has(t, 'diagram'), unit: has(t, 'calculation'), rationale: has(t, 'calculation') };
}
function field(id, label, kind, extra = {}) { return { id, label, kind, enabled: true, ...extra }; }
function commonFields(exam, makeId) { return {
  examName: exam?.cover?.examName || '建築設備士試験 第二次試験（設計製図）', mockLabel: exam?.cover?.mockLabel || '模擬試験', designTaskName: exam?.projectTitle || exam?.cover?.designTaskName || '',
  examineeNumber: field(makeId('answer-common-examinee-number'), '受験番号', 'text', { width: '45mm' }), name: field(makeId('answer-common-name'), '氏名', 'text', { width: '60mm' }), sheetNumber: field(makeId('answer-common-sheet-number'), '答案用紙番号', 'text'), selectedDiscipline: field(makeId('answer-common-selected-discipline'), '選択設備区分', 'checkbox'), pageNumber: field(makeId('answer-common-page-number'), 'ページ番号', 'text'), scorerArea: field(makeId('answer-common-scorer'), '採点者記入欄', 'scorer'), notices: field(makeId('answer-common-notices'), '注意事項欄', 'notice', { text: '模範解答は含まれていません。黒鉛筆等で記入・作図してください。' })
}; }
function questionBlock(q, sheetType, prefix, makeId) { const en = enabledAreas(q.answerType); const base = `answer-${prefix}${String(q.number || q.questionId).replace(/[^a-z0-9]/gi, '').toLowerCase()}`; const areas = {
  description: field(makeId(`${base}-description`), '記述欄', 'description', { enabled: en.description }), calculation: field(makeId(`${base}-calculation`), '計算欄', 'calculation', { enabled: en.calculation }), selection: field(makeId(`${base}-selection`), '選択欄', 'selection', { enabled: en.selection }), diagram: field(makeId(`${base}-diagram`), '簡易図示欄', 'diagram', { enabled: en.diagram }), unit: field(makeId(`${base}-unit`), '単位記入欄', 'unit', { enabled: en.unit }), rationale: field(makeId(`${base}-rationale`), '算定根拠欄', 'rationale', { enabled: en.rationale })
}; return { questionId: q.questionId, number: q.number, title: q.title, answerType: q.answerType, answerSheetAreaId: q.answerSheetAreaId, drawingRequirements: q.drawingRequirements || [], areas, primaryAnswerSheetId: Object.values(areas).find((a) => a.enabled)?.id || areas.description.id, sheetType }; }
function electiveSheet(key, title, questions, makeId) { const labels = key === 'hvac' ? ['能力算定表','系統図欄','平面図欄','部分詳細図欄','機器表・凡例・制御説明欄'] : key === 'plumbing' ? ['給水・給湯・排水能力算定表','給排水衛生設備系統図欄','平面図欄','給水設備室または給湯設備室詳細図欄','機器表・凡例・雨水利用・消火設備説明欄'] : ['受変電容量・非常電源容量算定表','受変電単線結線図欄','平面図欄','幹線系統図または受変電室詳細図欄','負荷表・機器表・凡例・制御説明欄']; const sheetType = `${key}Sheet`; const qbs = (questions || []).map((q, i) => ({ ...questionBlock(q, sheetType, `${key === 'hvac' ? 'hvac' : key}-q${i + 1}`, makeId), sectionTitle: `第${i + 1}問 ${labels[i]}` })); const columns = key === 'electrical' ? ['負荷名称','設備容量','需要率','需要電力','力率','備考'] : key === 'plumbing' ? ['項目','容量','流量','管径','時間','算定根拠','備考'] : ['項目','算定結果','単位','算定根拠','備考']; return { sheetId: makeId(`answer-${key}-sheet`), sheetType, title, size: 'A3-landscape', questions: qbs, calculationTable: { id: makeId(`answer-${key}-q1-calculation-table`), columns }, systemDiagramArea: { id: makeId(`answer-${key}-q2-${key === 'electrical' ? 'single-line' : 'system-diagram'}`), labels: key === 'hvac' ? ['空調熱源設備','冷温水系統','冷却水系統','外気処理系統','排煙系統'] : key === 'plumbing' ? ['飲料水','雑用水','給湯','返湯','汚水','雑排水','厨房排水','雨水','通気','消火'] : ['受電点','高圧盤','変圧器','低圧盤','非常用発電機','蓄電池','常用系統','非常系統'] }, floorPlanArea: { id: makeId(`answer-${key}-q3-floor-plan`), blankPlanReference: true, includeModelAnswer: false, labels: ['指定階白図参照','作図範囲枠','凡例欄','注記欄','機器番号欄'] }, detailArea: { id: makeId(`answer-${key}-q4-detail`), labels: key === 'hvac' ? ['空調熱源設備室','屋上設備置場','機械室','維持管理スペース記入欄'] : ['設備室','維持管理スペース記入欄','搬入経路'] }, scheduleLegendArea: { id: makeId(`answer-${key}-q5-schedule-legend`), labels: ['機器表','凡例欄','記述欄','採点者欄'] } }; }
function generateAnswerSheets({ exam, materials, drawings, options = {} } = {}) { const makeId = makeIdFactory(); const set = { answerSheetSetId: makeId(`answer-sheet-set-${exam?.examId || Date.now()}`), examId: exam?.examId || '', sheetSizePolicy: { written: 'A4-portrait', drawing: 'A3-landscape' }, commonFields: commonFields(exam, makeId), mandatoryPlanningSheet: { sheetId: makeId('answer-mandatory-planning-sheet'), sheetType: 'mandatoryPlanningSheet', title: '建築設備基本計画答案用紙', size: 'A4-portrait', questions: (exam?.mandatoryQuestions || []).map((q) => questionBlock(q, 'mandatoryPlanningSheet', `m${String(q.number).padStart(2, '0')}`, makeId)) }, hvacSheet: electiveSheet('hvac', '空調・換気設備答案用紙', exam?.electiveSections?.hvac, makeId), plumbingSheet: electiveSheet('plumbing', '給排水衛生設備答案用紙', exam?.electiveSections?.plumbing, makeId), electricalSheet: electiveSheet('electrical', '電気設備答案用紙', exam?.electiveSections?.electrical, makeId), commonDescriptionSheet: { sheetId: makeId('answer-common-description-sheet'), sheetType: 'commonDescriptionSheet', title: '共通記述用紙', size: 'A4-portrait', pages: [{ page: 1, areas: ['description','calculation','diagram','extra'].map((k, i) => field(makeId(`answer-common-${k === 'extra' ? 'extra-01' : k}`), ['記述欄','計算欄','図示欄','追加答案欄'][i], k)) }] }, metadata: { generator: 'answerSheetGenerator', schemaVersion: '1.0.0', material5Reference: (Array.isArray(materials) ? materials : materials?.materials || []).find((m) => m?.materialId === 'material-5')?.materialId || 'material-5', blankPlanReferences: (drawings?.blankPlans || []).map((p) => p.drawingId), includeBlankPlanBackground: !!options.includeBlankPlanBackground, noModelAnswer: true } };
 set.questionAnswerMap = [...set.mandatoryPlanningSheet.questions, ...set.hvacSheet.questions, ...set.plumbingSheet.questions, ...set.electricalSheet.questions].map((q) => ({ questionId: q.questionId, answerSheetId: q.primaryAnswerSheetId, sheetType: q.sheetType, answerSheetAreaId: q.answerSheetAreaId })); return set; }
function collectIds(o, out = []) { if (!o || typeof o !== 'object') return out; if (o.id) out.push(o.id); if (o.sheetId) out.push(o.sheetId); Object.values(o).forEach((v) => Array.isArray(v) ? v.forEach((x) => collectIds(x, out)) : collectIds(v, out)); return out; }
function validateAnswerSheets(set, exam) { const errors = [], warnings = [], checks = []; const check = (name, ok, warn=false) => { checks.push({ name, ok: !!ok }); if (!ok) (warn ? warnings : errors).push(`${name}の検査に失敗しました。`); };
 check('必須答案用紙', !!set?.mandatoryPlanningSheet); check('選択答案用紙', !!set?.hvacSheet && !!set?.plumbingSheet && !!set?.electricalSheet); check('必須11問', set?.mandatoryPlanningSheet?.questions?.length === 11); ['hvac','plumbing','electrical'].forEach((k) => check(`${k}5問`, set?.[`${k}Sheet`]?.questions?.length === 5)); const ids = collectIds(set); check('ID重複なし', ids.length === new Set(ids).size); const mapIds = new Set((set?.questionAnswerMap || []).map((m) => m.questionId)); [...(exam?.mandatoryQuestions || []), ...Object.values(exam?.electiveSections || {}).flat()].forEach((q) => check(`対応表:${q.questionId}`, mapIds.has(q.questionId))); const blocks = [...(set?.mandatoryPlanningSheet?.questions || []), ...(set?.hvacSheet?.questions || []), ...(set?.plumbingSheet?.questions || []), ...(set?.electricalSheet?.questions || [])]; blocks.forEach((b) => { const en = enabledAreas(b.answerType); if (en.description) check(`${b.questionId}記述欄`, b.areas.description.enabled); if (en.calculation) check(`${b.questionId}計算欄`, b.areas.calculation.enabled && b.areas.unit.enabled); if (en.diagram) check(`${b.questionId}作図欄`, b.areas.diagram.enabled || /q[234]/i.test(b.primaryAnswerSheetId)); }); check('資料5整合', !!set?.metadata?.material5Reference, true); check('模範解答なし', !JSON.stringify(set || {}).includes('模範解答:') && !JSON.stringify(set || {}).includes('modelAnswer')); check('印刷用紙サイズ', set?.sheetSizePolicy?.written === 'A4-portrait' && set?.sheetSizePolicy?.drawing === 'A3-landscape'); return { isValid: errors.length === 0, errors, warnings, checks }; }
if (typeof module !== 'undefined') module.exports = { generateAnswerSheets, validateAnswerSheets };
if (typeof window !== 'undefined') { window.generateAnswerSheets = generateAnswerSheets; window.validateAnswerSheets = validateAnswerSheets; }
