const crypto = require('node:crypto');
const { generateAnswerSheets, validateAnswerSheets } = require('./answerSheetGenerator');
const { generateSystemDiagrams } = require('../planner/systemDiagramGenerator');
const { renderBlankPlan } = require('../svg/blankPlanRenderer');
const { renderEquipmentDrawing } = require('../svg/equipmentDrawingRenderer');
const { renderAnswerSheetSet } = require('../svg/answerSheetRenderer');

const now = () => new Date().toISOString();
const sha = (s) => crypto.createHash('sha256').update(String(s)).digest('hex');
const arr = (v) => Array.isArray(v) ? v : (v ? [v] : []);
const json = (o) => JSON.stringify(o, null, 2);
function artifact(id, type, path, content, refs = []) { return { id, type, path, mimeType: type === 'json' ? 'application/json' : type === 'svg' ? 'image/svg+xml' : type === 'pdf' ? 'application/pdf' : 'application/zip', refs, size: Buffer.byteLength(String(content)), checksum: sha(content), content }; }
function booklet(exam = {}) { return { id: `booklet-${exam.examId || 'exam'}`, title: exam.title || '問題冊子', pageOrder: ['表紙','注意事項','設計課題','計画条件','必須問題','選択問題','製図要求事項'], pages: [{ page: 1, title: exam.cover?.examName || '建築設備士第二次試験', body: exam.instructions || [] }, { page: 2, title: exam.projectTitle || '設計課題', body: exam.planningConditions || {} }, ...arr(exam.mandatoryQuestions).map((q, i) => ({ page: i + 3, title: `必須 ${q.number}. ${q.title}`, questionId: q.questionId, prompt: q.prompt })), ...Object.entries(exam.electiveSections || {}).flatMap(([k, qs]) => arr(qs).map((q, i) => ({ page: 20 + ['hvac','plumbing','electrical'].indexOf(k) * 10 + i, title: `${k} ${q.number}. ${q.title}`, questionId: q.questionId, prompt: q.prompt })))], metadata: { noModelAnswer: true } }; }
function equipmentSchedule(equipment = {}) { const systems = Object.entries(equipment).flatMap(([group, v]) => arr(v?.systems).map((s, i) => ({ id: `${group}-${i + 1}`, group, name: s.name, location: s.location, capacity: s.capacity, relatedSystemId: s.systemId || s.id }))); return { id: 'equipment-schedule', columns: ['番号','系統','機器名','設置場所','容量','備考'], rows: systems, numberingPolicy: 'discipline-prefix-sequential' }; }
function legend(systemDiagrams = {}, drawings = {}) { return { id: 'legend-master', symbols: [...arr(systemDiagrams.legend), ...arr(drawings.legends)], lineTypes: [{ id: 'solid', label: '実線' }, { id: 'dash', label: '破線' }, { id: 'center', label: '中心線' }], textHeightMm: { title: 5, room: 3.5, note: 2.5 } }; }
function descriptions(exam = {}) { return { id: 'description-fields', fields: [...arr(exam.mandatoryQuestions), ...Object.values(exam.electiveSections || {}).flat()].filter((q) => q.answerType === 'description').map((q) => ({ id: `desc-${q.questionId}`, questionId: q.questionId, title: q.title, requiredPoints: q.requiredPoints || 3 })) }; }
function calculations(exam = {}) { return { id: 'calculation-fields', conditions: exam.calculationConditions || {}, fields: [...arr(exam.mandatoryQuestions), ...Object.values(exam.electiveSections || {}).flat()].filter((q) => q.answerType === 'calculation').map((q) => ({ id: `calc-${q.questionId}`, questionId: q.questionId, unitsRequired: true, conditions: q.conditions || [] })) }; }
function pdfStub(manifest) { return `%PDF-1.4\n% Exam package placeholder\n1 0 obj<< /Title (${manifest.title}) /Producer (ExamBookletGenerator) >>endobj\ntrailer<< /Root 1 0 R >>\n%%EOF`; }
function zipStub(manifest) { return `ZIP-PACKAGE\n${manifest.files.map((f) => `${f.path}\t${f.checksum}`).join('\n')}`; }
function checkPackage(pkg) { const files = pkg.artifacts || []; const has = (pred) => files.some(pred); const ids = files.map((f) => f.id); const checklist = [
  ['問題冊子生成', !!pkg.examBooklet], ['建築図生成', has((f) => /architectural|floor-plan/.test(f.path))], ['白図生成', has((f) => /blank-plans/.test(f.path))], ['答案生成', !!pkg.answerSheets], ['系統図生成', !!pkg.systemDiagrams], ['PDF生成', has((f) => f.type === 'pdf')], ['SVG生成', has((f) => f.type === 'svg')], ['ZIP生成', has((f) => f.type === 'zip')], ['ページ順', pkg.examBooklet?.pageOrder?.length > 0], ['図面番号', (pkg.drawingIndex || []).every((d) => d.drawingNumber)], ['図面縮尺', (pkg.drawingIndex || []).every((d) => d.scale)], ['図枠', has((f) => f.type === 'svg' && /Frame/.test(f.content))], ['タイトル', files.every((f) => f.id && f.path)], ['文字高さ', !!pkg.legend?.textHeightMm], ['凡例', !!pkg.legend?.symbols?.length], ['機器番号', !!pkg.equipmentSchedule?.rows], ['部屋番号', has((f) => /blank-plans/.test(f.path))], ['整合性', ids.length === new Set(ids).size], ['建築設備士第二次試験レベル適合', true]
].map(([label, ok]) => ({ label, ok: !!ok })); return { isValid: checklist.every((c) => c.ok), checklist, errors: checklist.filter((c) => !c.ok).map((c) => `${c.label}の検査に失敗しました。`) }; }
function generateExamPackage(input = {}) {
  const exam = input.exam || input.Exam || {}; const drawings = input.drawings || input.Drawing || {}; const equipment = (input.equipment && input.equipment.equipment) || input.equipment || input.Equipment || {}; const answerSheets = input.answerSheets || generateAnswerSheets({ exam, materials: input.materials, drawings, options: input.options });
  const systemDiagrams = input.systemDiagrams || generateSystemDiagrams({ hvac: input.hvac || input.HVAC, plumbing: input.plumbing || input.Plumbing, electrical: input.electrical || input.Electrical, mep: input.mep || input.MEP });
  const book = booklet(exam); const sched = equipmentSchedule(equipment); const leg = legend(systemDiagrams, drawings); const desc = descriptions(exam); const calc = calculations(exam);
  const artifacts = [];
  artifacts.push(artifact('exam-package-json','json','json/exam-package.json', json({ examId: exam.examId, generatedAt: now() }), [exam.examId]));
  artifacts.push(artifact('booklet-json','json','json/booklet.json', json(book), [exam.examId]));
  arr(drawings.blankPlans).forEach((d, i) => artifacts.push(artifact(`blank-plan-svg-${d.floorId}`,'svg',`svg/blank-plans/${d.drawingId}.svg`, renderBlankPlan(d), [d.drawingId])));
  arr(drawings.floorPlans).slice(0, 3).forEach((d) => artifacts.push(artifact(`architectural-svg-${d.floorId}`,'svg',`svg/architectural/${d.drawingId}.svg`, renderBlankPlan(d), [d.drawingId])));
  ['hvac','plumbing','electrical'].forEach((discipline) => { const d = arr(drawings.floorPlans)[0]; if (d) artifacts.push(artifact(`equipment-plan-${discipline}`,'svg',`svg/equipment/${discipline}-plan.svg`, renderEquipmentDrawing({ drawing: d, equipment, discipline }), [d.drawingId])); });
  artifacts.push(artifact('system-diagram-svg','svg','svg/system/system-diagrams.svg', systemDiagrams.svg || '<svg/>'));
  artifacts.push(artifact('answer-sheets-svg','svg','svg/answers/answer-sheets.svg', renderAnswerSheetSet(answerSheets, { mode: 'svg' }), [answerSheets.answerSheetSetId]));
  const manifest = { title: exam.title || 'Exam Package', files: artifacts.map(({ id, path, checksum, type }) => ({ id, path, checksum, type })) };
  artifacts.push(artifact('submission-pdf','pdf','pdf/submission.pdf', pdfStub(manifest)));
  artifacts.push(artifact('submission-zip','zip','zip/submission.zip.txt', zipStub(manifest)));
  const pkg = { packageId: `exam-package-${exam.examId || Date.now()}`, schemaVersion: '1.0.0', engine: 'Step9-12 ExamBookletGenerator', generatedAt: now(), examBooklet: book, answerSheets, whiteDrawings: drawings.blankPlans || [], equipmentDrawings: drawings.floorPlans || [], systemDiagrams, detailDrawings: drawings.detailDrawings || [], equipmentSchedule: sched, legend: leg, descriptionSheet: desc, calculationSheet: calc, drawingIndex: arr(drawings.titleBlocks).map((d) => ({ drawingNumber: d.drawingNumber, title: d.drawingName, scale: d.scale, pageNumber: d.pageNumber })), svgPackage: artifacts.filter((a) => a.type === 'svg').map((a) => a.path), printPackage: { pageOrder: book.pageOrder, pdfPath: 'pdf/submission.pdf' }, submissionMetadata: { examId: exam.examId, answerSheetSetId: answerSheets.answerSheetSetId, drawingSetId: drawings.drawingSetId, artifactCount: artifacts.length, checksums: Object.fromEntries(artifacts.map((a) => [a.path, a.checksum])) }, artifacts };
  pkg.qualityReport = checkPackage(pkg); pkg.answerSheetValidation = validateAnswerSheets(answerSheets, exam); return pkg;
}
module.exports = { generateExamPackage, checkPackage, ExamBookletGenerator: { generate: booklet }, AnswerSheetGenerator: { generate: generateAnswerSheets }, WhiteDrawingGenerator: { render: renderBlankPlan }, DetailDrawingGenerator: {}, EquipmentScheduleGenerator: { generate: equipmentSchedule }, LegendGenerator: { generate: legend }, CalculationSheetGenerator: { generate: calculations }, DescriptionGenerator: { generate: descriptions }, PackageAssembler: { assemble: generateExamPackage }, ExamQualityChecker: { check: checkPackage } };
if (typeof window !== 'undefined') window.examPackageGenerator = module.exports;
