function root(input, key) { return input && input[key] ? input[key] : input; }
function listMaterials(materials) { return Array.isArray(materials) ? materials : materials?.materials || []; }
function material(materials, id) { return listMaterials(materials).find((m) => m?.materialId === id); }
function areaText(a) { return a?.value ? `${a.value.toLocaleString('ja-JP')}${a.unit || 'm2'}` : '未設定'; }
function sys(e, group, index = 0) { return e?.[group]?.systems?.[index] || {}; }
function capText(s) { return s?.capacity ? `${s.capacity.value.toLocaleString('ja-JP')}${s.capacity.unit}` : '条件による'; }
function floorIds(drawings) { return (drawings?.floorPlans || drawings?.blankPlans || []).map((f) => String(f.floorId)); }
function seedFrom(building) { return String(building?.name || '').split('').reduce((s, c) => s + c.charCodeAt(0), 0); }
function pick(arr, n) { return arr[n % arr.length]; }

function makeQuestion(id, number, category, title, prompt, answerType, extra = {}) {
  return { questionId: id, number, category, title, prompt, answerType, requiredPoints: extra.requiredPoints || 3, conditions: extra.conditions || [], relatedSystems: extra.relatedSystems || [], relatedRooms: extra.relatedRooms || [], difficulty: extra.difficulty || 'standard', answerSheetAreaId: extra.answerSheetAreaId || 'basic-plan-description' };
}

function generateMandatory(b, e) {
  const rooms = b.rooms || {};
  const total = areaText(b.totalFloorArea);
  return [
    makeQuestion('M01', 1, '空調設備', '用途別空調ゾーニング計画', `${b.use}、客室${rooms.guestRooms}室、宴会場・レストランを持つ本建物で、客室、宴会場、厨房、ロビーの空調系統を分ける理由を3点述べよ。`, 'description', { relatedSystems: ['central-heat-source', 'guestroom-fcu'], relatedRooms: ['客室', '宴会場', '厨房', 'ロビー'] }),
    makeQuestion('M02', 2, '換気設備', '厨房換気量と給気バランス', `厨房面積${areaText(rooms.kitchen?.area)}、厨房排気能力${capText(sys(e, 'hvac', 3))}を踏まえ、臭気拡散と負圧過大を避ける計画上の配慮を述べよ。`, 'description', { relatedSystems: ['kitchen-ventilation'], relatedRooms: ['厨房'] }),
    makeQuestion('M03', 3, '給排水衛生設備', '設計給水量の算定', `設計人員${b.occupancy?.totalDesignPopulation || rooms.guestRooms * 2}人、受水槽容量${capText(sys(e, 'waterSupply'))}を用い、日使用水量と受水槽容量の妥当性を検討せよ。`, 'calculation', { conditions: ['一人一日給水量', '安全率'], relatedSystems: ['water-supply'], answerSheetAreaId: 'basic-plan-calculation' }),
    makeQuestion('M04', 4, '給湯設備', '中央給湯循環の衛生管理', `給湯能力${capText(sys(e, 'hotWater'))}の中央給湯方式について、返湯温度管理、滞留防止、レジオネラ属菌対策を含めて説明せよ。`, 'description', { relatedSystems: ['hot-water'], relatedRooms: ['客室', 'SPA', '厨房'] }),
    makeQuestion('M05', 5, '排水通気設備', '排水系統分離と通気計画', `客室系統、厨房排水、地下階排水を対象に、汚水・雑排水分流、グリース阻集器、通気管の計画要点を述べよ。`, 'diagram', { relatedSystems: ['drainage'], relatedRooms: ['客室', '厨房', '地下階'] }),
    makeQuestion('M06', 6, '消火設備・防災', 'ホテル用途の防災設備', `消防法上の用途区分を踏まえ、スプリンクラー、屋内消火栓、非常電源、防火区画貫通処理の計画要点を述べよ。`, 'description', { relatedSystems: ['sprinkler', 'emergency-generator'], difficulty: 'hard' }),
    makeQuestion('M07', 7, '電気設備', '受変電容量の算定', `延べ面積${total}、需要電力${capText(sys(e, 'electrical'))}、変圧器容量${capText(sys(e, 'receivingTransformer'))}から、需要率を考慮した受変電容量を検討せよ。`, 'calculation', { conditions: ['照明負荷', 'コンセント負荷', '需要率', '力率'], relatedSystems: ['receiving-transformer'], answerSheetAreaId: 'basic-plan-calculation' }),
    makeQuestion('M08', 8, '非常電源・BCP', '停電時継続運転範囲', `非常用発電機${capText(sys(e, 'emergencyPower'))}で供給する防災負荷と保安負荷を区分し、72時間運用を想定したBCP上の優先順位を述べよ。`, 'selection', { relatedSystems: ['emergency-generator', 'sprinkler'] }),
    makeQuestion('M09', 9, '自動制御・BEMS', '中央監視とエネルギー管理', `中央監視・BEMSにより、熱源、外気処理、照明、受変電を監視制御する項目を、本ホテルの運営条件に合わせて3点述べよ。`, 'description', { relatedSystems: ['bems', 'lighting-control'] }),
    makeQuestion('M10', 10, '維持管理・設備更新', '設備更新と保守動線', `地下機械室、1階受変電室、屋上設備置場について、搬入経路、点検スペース、営業継続中の更新計画の留意点を述べよ。`, 'description', { relatedRooms: ['空調熱源設備室', '受変電室', '屋上設備置場'] }),
    makeQuestion('M11', 11, '設備横断・LCC', '省エネルギーとLCCの総合評価', `空調、給湯、照明、BEMSを横断し、ZEB Oriented相当の省エネルギーとLCC低減を両立する提案を3点示せ。`, 'description', { relatedSystems: ['central-heat-source', 'hot-water', 'lighting-control', 'bems'], difficulty: 'hard' })
  ];
}

function elective(prefix, titles, floor, systemTarget, sheet) { return titles.map((t, i) => makeQuestion(`${prefix}${String(i + 1).padStart(2, '0')}`, i + 1, sheet, t[0], t[1], t[2], { conditions: t[3], relatedSystems: t[4], relatedRooms: t[5], answerSheetAreaId: `${prefix.toLowerCase()}-${i + 1}` })); }

function generateExam({ plan, building, equipment, materials, drawings, options = {} } = {}) {
  const b = root(building, 'building'); const e = root(equipment, 'equipment');
  if (!b) throw new Error('buildingが存在しません。'); if (!e) throw new Error('equipmentが存在しません。');
  const seed = seedFrom(b); const applicableLawDate = options.applicableLawDate || '2026-01-01';
  const floor = pick(['2', '3', '4-10'], seed); const projectTitle = pick([`${b.rooms?.banquetHall?.area?.value ? '宴会場' : '会議室'}及びレストランを併設した都市型ホテル`, `地域交流機能を備えた複合シティホテル`, `国際滞在客に対応するフルサービスホテル`], seed);
  const material5 = material(materials, 'material-5');
  const calculationConditions = { outdoorAir: { summer: '34℃DB/27℃WB', winter: '2℃DB' }, indoor: { guestRoom: '26℃・50%', banquet: '25℃・50%' }, airDensity: '1.2kg/m3', waterSpecificHeat: '4.19kJ/(kg・K)', chilledWaterDeltaT: '5℃', hotWaterDeltaT: '10℃', enthalpyDifference: '52kJ/kg', lightingLoad: '12W/m2', receptacleLoad: '18VA/m2', demandFactor: 0.72, powerFactor: 0.9, waterPerPersonPerDay: '350L/人日', hotWaterPerGuest: '55L/h', simultaneityFactor: 0.65, safetyFactor: 1.15 };
  const mandatoryQuestions = generateMandatory(b, e);
  const electiveSections = {
    hvac: elective('A', [['空調機能力算定', `${floor}階の外気処理空調機又は宴会場空調機の能力を、外気条件、室内条件、比エンタルピー差により算定せよ。`, 'calculation', ['外気条件', '室内条件', '空気密度', '比エンタルピー'], ['central-heat-source'], ['宴会場']], ['熱源・冷温水配管系統図', '熱源機、ポンプ、膨張タンク、ヘッダー、自動制御弁を含む系統図を作図せよ。凡例、配管径条件、防火区画貫通処理を記載すること。', 'diagram', ['縮尺: 図示', '凡例必須'], ['central-heat-source'], ['空調熱源設備室']], [`${floor}階空調・換気設備平面図`, 'ダクト又は配管ルート、吹出口、吸込口、FD、VD、点検口、維持管理スペースを白図上に記入せよ。', 'diagram', ['縮尺1/200', `作図対象階:${floor}`], ['guestroom-fcu', 'outdoor-air-supply'], ['客室', '廊下']], ['屋上設備部分詳細図', '屋外機、厨房排気ファン、離隔距離、防振、保守スペースを1/50程度で示せ。', 'diagram', ['縮尺1/50'], ['kitchen-ventilation'], ['屋上設備置場']], ['機器表・制御・省エネルギー', '主要機器表、VAV/インバータ制御、BEMS計量点、熱源台数制御を記載せよ。', 'description', ['機器表対象:熱源・AHU・ファン'], ['bems'], []]], floor, '熱源系統', '空調・換気設備'),
    plumbing: elective('B', [['給水・給湯・排水能力算定', '飲料水、雑用水、給湯・返湯、汚水・雑排水、厨房排水の容量又は管径条件を算定せよ。', 'calculation', ['給水量', '給湯量', '同時使用率'], ['water-supply', 'hot-water', 'drainage'], ['客室', '厨房']], ['給排水衛生設備系統図', '受水槽、加圧給水、雑用水、給湯返湯、排水通気、雨水、消火配管を区分して作図せよ。', 'diagram', ['凡例必須'], ['water-supply', 'sprinkler'], []], [`${floor}階給排水衛生設備平面図`, 'PS、器具、配管ルート、通気、清掃口、厨房排水系統、防火区画貫通処理を記入せよ。', 'diagram', [`作図対象階:${floor}`, '縮尺1/200'], ['drainage'], ['客室', '厨房']], ['給水又は給湯設備室詳細図', '受水槽、ポンプ、熱源、ヘッダー、点検・清掃・更新スペースを示せ。', 'diagram', ['縮尺1/50'], ['water-supply', 'hot-water'], ['給水設備室']], ['機器表・雨水利用・消火設備', 'ポンプ・タンク機器表、雨水利用、消火設備の非常電源接続を記載せよ。', 'description', ['容量条件'], ['sprinkler'], []]], floor, '給排水系統', '給排水衛生設備'),
    electrical: elective('C', [['受変電容量・非常電源容量算定', '受電方式、変圧器、非常用発電機について需要率、力率、安全率を用いて容量を算定せよ。', 'calculation', ['需要率', '力率', '安全率'], ['receiving-transformer', 'emergency-generator'], ['受変電室']], ['受変電単線結線図', '高圧受電、変圧器、常用・非常系統、保護継電器、計測、BEMS連携を示せ。', 'diagram', ['凡例必須'], ['receiving-transformer'], ['受変電室']], [`${floor}階電気設備平面図`, '幹線、分電盤、動力盤、照明、非常照明、誘導灯、火災報知、中央監視配線を記入せよ。', 'diagram', [`作図対象階:${floor}`, '縮尺1/200'], ['lighting-control', 'bems'], ['客室', '廊下']], ['幹線系統図又は受変電室詳細図', 'EPS、幹線サイズ区分、保守点検スペース、搬入経路、非常系統と常用系統の分離を示せ。', 'diagram', ['縮尺1/50又は図示'], ['power-distribution'], ['EPS']], ['負荷表・照明制御・中央監視', '用途別負荷表、照明制御、火災報知、中央監視、BEMSポイント表を記載せよ。', 'description', ['機器表対象:変圧器・発電機・盤'], ['bems', 'lighting-control'], []]], floor, '受変電', '電気設備')
  };
  const drawingRequirements = { disciplines: ['空調・換気設備', '給排水衛生設備', '電気設備'], targetDrawings: ['系統図', '平面図', '部分詳細図', '機器表', '凡例'], targetFloors: [floor], scale: { plan: '1/200', detail: '1/50', system: '図示' }, sheetSize: drawings?.sheetSize || 'A3-landscape', systemDiagrams: ['熱源', '給排水', '受変電'], legends: drawings?.legends?.map((l) => l.symbolId) || [], symbols: ['FD', 'VD', 'PS', 'EPS', 'DS', 'SP', 'ELB'], requiredNotes: ['防火区画貫通処理', '維持管理スペース', '系統名・凡例'], omittableItems: ['軽微な寸法', '家具詳細'], blankPlanReferences: (drawings?.blankPlans || []).map((d) => d.drawingId), answerSheetReferences: (drawings?.answerSheets || []).map((s) => s.sheetId) };
  const answerSheetReferences = { mandatory: material5?.answerSheets?.[0]?.sheetId || 'basic-plan', hvac: 'hvac-ventilation', plumbing: 'plumbing-sanitary', electrical: 'electrical', description: 'description', calculation: 'calculation', systemDiagram: 'systemDiagram', plan: 'planDrawing', equipmentSchedule: 'equipmentSchedule', legend: 'legend' };
  return { examId: `exam-${Date.now()}`, version: '1.0', title: '建築設備士試験 第二次試験（設計製図） 模擬試験', projectTitle, createdAt: new Date().toISOString(), durationMinutes: 330, applicableLawDate, cover: { examName: '建築設備士試験 第二次試験（設計製図）', mockLabel: '模擬試験', designTaskName: projectTitle, bookletLabel: '問題集', duration: '330分', examineeNumberField: '受験番号欄', nameField: '氏名欄', noticeGuide: '注意事項を確認してから解答すること。', learningLabel: '学習用模擬試験' }, instructions: ['問題集は表紙、注意事項、設計課題、計画条件、必須問題、選択問題、製図要求事項で構成する。', '建築設備基本計画は必須問題である。', '基本設計製図は空調・換気、給排水衛生、電気から1区分を選択する。', '資料5の答案用紙を使用する。', '黒鉛筆又はシャープペンを使用する。', 'フリーハンド作図可。', `適用法令日は${applicableLawDate}とする。`, '問題文と図面の整合を確認すること。', '模範解答は問題集に含めない。'], designTask: { buildingUse: b.use, hotelType: plan?.hotelTypeName || plan?.hotelType || b.planningSource?.hotelTypeName || b.planningSource?.hotelType || '都市型ホテル', concept: b.concept, primaryAdditionalUses: ['宴会場', 'レストラン', '厨房', 'SPA'].filter((name) => JSON.stringify(b.rooms || {}).includes(name === 'SPA' ? 'spa' : name === '厨房' ? 'kitchen' : name === '宴会場' ? 'banquetHall' : 'restaurant')), locationConditions: b.siteCondition, designFocus: ['安全性', '省エネルギー', 'BCP', '維持管理性', '宿泊快適性'] }, planningConditions: { buildingSummary: b.name, use: b.use, fireServiceUseCategory: 'ホテル（消防法施行令別表第一(5)項イ相当）', location: b.location, zoning: b.zoning, siteArea: b.siteArea, buildingArea: b.buildingArea, totalFloorArea: b.totalFloorArea, structure: b.structure, floors: b.floors, penthouse: b.floors?.penthouse, basement: b.floors?.basement, guestRooms: b.rooms?.guestRooms, users: b.occupancy, parking: { bays: Math.max(20, Math.ceil((b.rooms?.guestRooms || 0) * 0.18)) }, infrastructure: material(materials, 'material-2')?.utilityConnectionPoints || {}, operation: { hours: '宿泊24時間、料飲・宴会は時間帯運用' }, disasterPrevention: { fireCompartment: '用途・竪穴区画を設定', smokeControl: '避難安全と整合' }, energySaving: { target: 'ZEB Oriented相当を検討' }, bcp: { emergencyPower: capText(sys(e, 'emergencyPower')), water: '受水槽と重要系統を優先' } }, mandatoryQuestions, electiveSections, drawingRequirements, calculationConditions, answerSheetReferences, metadata: { generator: 'examGenerator', schemaVersion: '1.0.0', sourceMaterialIds: listMaterials(materials).map((m) => m.materialId), drawingSetId: drawings?.drawingSetId, noModelAnswer: true } };
}

function createQuestionFingerprint(q) { const text = [q.title, q.prompt, q.answerType, ...(q.conditions || []), ...(q.relatedSystems || []), ...(q.relatedRooms || [])].join(' '); const words = text.replace(/[、。・（）()]/g, ' ').split(/\s+/).filter(Boolean); return { id: q.questionId, title: q.title, answerType: q.answerType, systems: q.relatedSystems || [], rooms: q.relatedRooms || [], keywords: [...new Set(words.filter((w) => w.length >= 2))].slice(0, 20), structure: (q.prompt || '').replace(/[0-9０-９]+/g, '#').slice(0, 80) }; }
function similarity(a, b) { const ak = new Set(a.keywords); const bk = new Set(b.keywords); const inter = [...ak].filter((x) => bk.has(x)).length; const union = new Set([...ak, ...bk]).size || 1; return inter / union + (a.title === b.title ? 0.5 : 0) + (a.answerType === b.answerType ? 0.05 : 0); }
function checkQuestionDuplication(questions) { const warnings = []; const fps = (questions || []).map(createQuestionFingerprint); for (let i = 0; i < fps.length; i += 1) for (let j = i + 1; j < fps.length; j += 1) if (similarity(fps[i], fps[j]) >= 0.72 || fps[i].structure === fps[j].structure) warnings.push(`${fps[i].id}と${fps[j].id}が過度に類似している可能性があります。`); return { hasDuplication: warnings.length > 0, warnings, fingerprints: fps }; }
function validateExam(exam, sources = {}) { const errors = []; const warnings = []; const b = root(sources.building, 'building'); const allQ = [...(exam?.mandatoryQuestions || []), ...Object.values(exam?.electiveSections || {}).flat()]; const validFloors = floorIds(sources.drawings); const checks = { cover: !!exam?.cover, instructions: (exam?.instructions || []).length > 0, designTask: !!exam?.designTask?.buildingUse, planningConditions: !!exam?.planningConditions?.totalFloorArea, mandatoryCount: exam?.mandatoryQuestions?.length === 11, electiveCounts: ['hvac', 'plumbing', 'electrical'].every((k) => exam?.electiveSections?.[k]?.length === 5), calculationConditions: !!exam?.calculationConditions && Object.keys(exam.calculationConditions).length > 0, drawingConsistency: (exam?.drawingRequirements?.blankPlanReferences || []).every((id) => (sources.drawings?.blankPlans || []).some((d) => d.drawingId === id)), answerSheetReferences: !!exam?.answerSheetReferences?.mandatory, buildingConsistency: !b || exam?.planningConditions?.guestRooms === b.rooms?.guestRooms, existingFloors: (exam?.drawingRequirements?.targetFloors || []).every((f) => validFloors.includes(String(f))), systemConsistency: allQ.every((q) => (q.relatedSystems || []).length === 0 || q.relatedSystems.every((id) => JSON.stringify(root(sources.equipment, 'equipment') || {}).includes(id))), nonEmptyPrompts: allQ.every((q) => q.prompt && q.title), noModelAnswer: !JSON.stringify(exam || {}).includes('模範解答:') && !Object.prototype.hasOwnProperty.call(exam || {}, 'modelAnswers') };
  const dup = checkQuestionDuplication(allQ); checks.noDuplication = !dup.hasDuplication; if (dup.hasDuplication) warnings.push(...dup.warnings); Object.entries(checks).forEach(([k, ok]) => { if (!ok) errors.push(`${k}の検査に失敗しました。`); }); return { isValid: errors.length === 0, errors, warnings, checks }; }
if (typeof module !== 'undefined') module.exports = { generateExam, createQuestionFingerprint, checkQuestionDuplication, validateExam };
if (typeof window !== 'undefined') { window.generateExam = generateExam; window.createQuestionFingerprint = createQuestionFingerprint; window.checkQuestionDuplication = checkQuestionDuplication; window.validateExam = validateExam; }
