const { extractQuestionBlankPlan } = require('./drawingExtractor');
function commonQuestions(common) { return Array.isArray(common) ? common : Object.values(common || {}); }
function arr(v) { return Array.isArray(v) ? v : v ? [v] : []; }
function textOf(q) { return [q?.prompt, q?.title, q?.type, q?.category, q?.roomType, q?.autoSelection?.roomType, q?.autoSelection?.targetScope, ...(q?.conditions || []), ...(q?.relatedSystems || []), ...(q?.drawingRequirements || [])].join(' '); }
const RuleBase = {
  floor(drawings, req) { const want = String(req?.targetFloor || req?.question?.autoSelection?.targetFloor || '').replace('階',''); return (drawings?.floorPlans || []).find((f) => String(f.floorId) === want) || (drawings?.floorPlans || [])[0] || {}; },
  density(plan, req) { const t = [req?.drawingDensity, req?.drawingPurpose, req?.roomType, req?.questionText].join(' '); if (/large|宴会|banquet|駐車|parking/.test(t)) return 'large'; if (/small|便所|UB|浴室|洗面|給湯|toilet|bath/.test(t)) return 'small'; return (plan?.rooms || []).length > 4 ? 'medium' : 'small'; },
  scale(candidates, plan, req) { if (req?.requiredScale) return req.requiredScale; const d = this.density(plan, req); if (d === 'large') return candidates.includes('1/150') ? '1/150' : candidates[candidates.length - 1]; if (d === 'small') return candidates[0]; return candidates.includes('1/100') ? '1/100' : candidates[0]; },
  margin(plan, req) { return Number(req?.margin) || (this.density(plan, req) === 'large' ? 6000 : this.density(plan, req) === 'small' ? 2500 : 4000); }
};
const HVACBlankPlanRule = { ...RuleBase, discipline: 'hvac', drawingType: 'hvac-blank-plan', scaleCandidates: ['1/100','1/150','1/200'], includePolicy: ['columns','walls','doors','windows','EPS','PS','DS','EV','stairs','roomNames','dimensions','north','equipmentRooms','equipmentShafts'], excludedEquipment: ['ducts','chilledHotWaterPipes','refrigerantPipes','drainPipes','FCU','PAC','AHU','VAV','CAV','diffusers','returnGrilles','FD','VD','accessPanels','insulation','equipmentSymbols'] };
const PlumbingBlankPlanRule = { ...RuleBase, discipline: 'plumbing', drawingType: 'plumbing-blank-plan', scaleCandidates: ['1/50','1/75','1/100'], includePolicy: ['columns','walls','doors','sanitaryFixtureOutlines','floorDrains','PS','DS','EPS','dimensions','roomNames','north','greaseInterceptor'], excludedEquipment: ['waterSupply','hotWater','drainage','vent','rainwater','fireProtection','valves','fixtureConnectionPipes','pipeDiameter'] };
const ElectricalBlankPlanRule = { ...RuleBase, discipline: 'electrical', drawingType: 'electrical-blank-plan', scaleCandidates: ['1/50','1/100'], includePolicy: ['columns','walls','doors','windows','furniture','roomNames','dimensions','ceilingHeight','north','calculationTable'], excludedEquipment: ['lighting','emergencyLighting','exitSigns','detectors','emergencyBroadcast','receptacles','switches','LAN','telephone','wiring','racks'] };
function ruleFor(x) { const qid = x?.questionId || x?.question?.questionId; if (qid === 'Q03') return HVACBlankPlanRule; if (qid === 'Q04') return PlumbingBlankPlanRule; if (qid === 'Q05') return ElectricalBlankPlanRule; const t = [x?.drawingType, qid, x?.type, x?.category, x?.questionText].join(' '); if (/Q04|plumbing|PLUMBING|衛生|排水|給水|厨房/.test(t)) return PlumbingBlankPlanRule; if (/Q05|electrical|ELECTRICAL|電気|照明|感知器/.test(t)) return ElectricalBlankPlanRule; return HVACBlankPlanRule; }
function analyzeQuestionRequirement({ question, questionText, buildingType, roomType, equipmentSystem, difficulty } = {}) {
  const qText = questionText || question?.prompt || question?.title || ''; const text = [qText, question?.title, question?.category, ...(question?.conditions || []), ...(question?.relatedSystems || [])].join(' ');
  const qid = question?.questionId; const rule = ruleFor({ ...question, questionText: text }); const isHvac = rule.discipline === 'hvac', isPlumbing = rule.discipline === 'plumbing', isElectrical = rule.discipline === 'electrical';
  const room = roomType || question?.roomType || question?.autoSelection?.roomType || question?.relatedRooms?.[0] || (/厨房/.test(text) ? '厨房' : /会議室/.test(text) ? '会議室' : isPlumbing ? '男子便所' : '客室');
  const systems = arr(equipmentSystem || question?.equipmentSystem || question?.autoSelection?.equipmentCondition || question?.relatedSystems);
  const requiredScale = question?.recommendedScale || (isPlumbing && /厨房|便所|UB|浴室|詳細/.test(text) ? '1/50' : isElectrical || isHvac ? '1/100' : '1/100');
  const hiddenEquipment = isHvac ? ['FCU','chilledHotWaterPipes','drainPipes','ducts'] : isPlumbing ? ['waterSupply','hotWater','drainage','vent','fixtureConnectionPipes'] : ['lighting','emergencyLighting','exitSigns','detectors','emergencyBroadcast','receptacles','switches','wiring'];
  return { questionId: qid, question, questionText: qText, buildingType: buildingType || question?.autoSelection?.buildingUse || 'ホテル', roomType: room, equipmentSystem: systems, difficulty: difficulty || question?.difficulty || question?.autoSelection?.examDifficulty || 'standard', drawingType: isHvac ? 'HVAC' : isPlumbing ? 'PLUMBING' : 'ELECTRICAL', drawingPurpose: qText || question?.title || '', requiredScale, cropRule: { type: 'target-room-with-margin', targetRoom: room, targetFloor: question?.autoSelection?.targetFloor }, targetFloor: question?.autoSelection?.targetFloor, requiredRooms: /客室/.test(room) && isHvac ? ['客室6室', '廊下'] : [room], requiredWalls: true, requiredDoors: true, requiredWindows: !isPlumbing, requiredColumns: true, requiredDimensions: true, requiredFurniture: isElectrical, requiredFixtures: isPlumbing ? (/厨房/.test(text) ? ['厨房器具輪郭','床排水','グリース阻集器','PS','EPS','建具','寸法'] : ['器具輪郭','床排水','PS','EPS','建具','寸法']) : isHvac ? ['UB','PS','EPS','建具','寸法'] : [], requiredEquipmentSymbols: isPlumbing && /厨房|グリース/.test(text) ? ['グリース阻集器位置'] : [], hiddenEquipment, drawingDensity: /宴会|厨房/.test(text) ? 'medium' : 'small', margin: /宴会/.test(text) ? 6000 : 2500, sheetPreference: 'AnswerSheet4', requiredTables: isElectrical || /計算|照度|台数/.test(text) ? ['計算表'] : [], requiredCalculationArea: isElectrical || /計算/.test(text) };
}
function requirementFromQuestion(q) { return q?.drawingRequirement || analyzeQuestionRequirement({ question: q }); }
function generateQuestionMetadata(question, req, scale, cropArea) { return { questionId: question?.questionId, category: question?.category, drawingType: req.drawingType, roomType: req.roomType, equipmentSystem: req.equipmentSystem || [], recommendedScale: scale, cropArea, drawingRule: req.drawingType, requiredSymbols: req.requiredEquipmentSymbols || [], requiredLegend: false, requiredDimension: !!req.requiredDimensions, requiredEquipment: [] }; }
function adaptiveLayout(req, plan) { const needTable = (req.requiredTables || []).length > 0 || req.requiredCalculationArea; return { title: `${req.questionId || ''} ${req.drawingType}答案レイアウト`.trim(), drawingNumber: `AS4-${req.questionId}`, north: '上', scale: req.requiredScale, frame: '本試験答案レイアウト', adaptive: true, printQualityDpi: 300, requiredAreaScore: (plan?.cropBox?.width || 1) * (plan?.cropBox?.height || 1), requiredCalculationArea: !!req.requiredCalculationArea, requiredTables: req.requiredTables || [], notesArea: needTable ? 'calculation-table' : 'legend-notes' }; }
function generateQuestionBlankPlans({ drawings, common, drawingRequirements } = {}) {
  const out = {}; const reqMap = drawingRequirements || {};
  commonQuestions(common).forEach((q) => { const req = reqMap[q.questionId] || reqMap[String(q.questionId || '').toLowerCase()] || requirementFromQuestion(q); const rule = ruleFor(req); const floorPlan = rule.floor(drawings, req); const scale = rule.scale(rule.scaleCandidates, floorPlan, req); const margin = rule.margin(floorPlan, req); const plan = extractQuestionBlankPlan({ floorPlan, question: { ...q, autoSelection: { ...(q.autoSelection || {}), roomType: req.roomType, targetFloor: req.targetFloor } }, scale, margin, rule, drawingRequirement: req });
    out[String(q.questionId || '').toLowerCase()] = { blankPlan: { ...plan, drawingRequirement: req, questionMetadata: generateQuestionMetadata(q, req, scale, plan.cropBox), sheetLayout: adaptiveLayout(req, plan), metadata: { ...plan.metadata, generator: 'QuestionBlankPlanGenerator', requirementAnalyzer: true, dynamicCropEngine: true, dynamicScaleEngine: true, adaptiveLayoutEngine: true, rule: rule.drawingType } } };
  }); return out;
}
function checkDrawingRequirementQuality(blankPlan) { const req = blankPlan?.drawingRequirement || {}; const checks = [ ['問題文と白図一致', !!req.questionText && blankPlan?.questionMetadata?.roomType === req.roomType], ['問題文と縮尺一致', blankPlan?.scale === req.requiredScale], ['問題文と切り出し範囲一致', !!blankPlan?.cropBox && blankPlan?.metadata?.targetOnly], ['問題文と設備方式一致', arr(req.equipmentSystem).every((s) => textOf(req.question || {}).includes(s) || JSON.stringify(req).includes(s))], ['問題文と表示情報一致', arr(req.hiddenEquipment).every((e) => (blankPlan?.excludedEquipment || []).includes(e) || JSON.stringify(blankPlan?.excludedEquipment || []).includes(e))], ['本試験レベル一致', blankPlan?.sheetLayout?.frame === '本試験答案レイアウト' && blankPlan?.sheetLayout?.adaptive] ]; return { isValid: checks.every(([, ok]) => ok), checks: checks.map(([label, ok]) => ({ label, ok })), errors: checks.filter(([, ok]) => !ok).map(([label]) => label) }; }
module.exports = { generateQuestionBlankPlans, analyzeQuestionRequirement, checkDrawingRequirementQuality, HVACBlankPlanRule, PlumbingBlankPlanRule, ElectricalBlankPlanRule, ruleFor };
